### ISSUE TITLE
await coll.update(..) seems not to wait as expected.

### ISSUE THREAD

**Issue by giorgiofran** [mongo-dart/mongo_dart#105]
I'm not sure if this is an issue or if there is something not clear to me in `await` use.

I have a function containing a `await collection.update(...)` instruction.
Before the update I have put a `print('Before')` statement and after a `print('After')` one.

Sometimes,  when I have more than one update I get this result:

> Before
> Before
> After
> After

The system executes other functions before getting back to the 'After' printout.

This is not what I expected, in the sense that I thought that the `await` function executed everything and then returned to the function before doing anything else.

I gave a look to the sources of mongo_dart, because I gues that it should not be a dart problem.

`Future<Map> update` is inside a `Future.Sync`, so, ASAIK, should be OK.

But, for example:
```

  Future<Map> _getAcknowledgement({WriteConcern writeConcern}) {
    if (writeConcern == null) {
      writeConcern = _writeConcern;
    }

    if (writeConcern == WriteConcern.ERRORS_IGNORED) {
      return new Future.value({'ok': 1.0});
    } else {
      return getLastError(writeConcern);
    }
  }
```
the `getLastError() `call is not under an `await `condition, so probably will not wait.

Am I right? 
If not please explain me why the `await` on the `collection.update()` call seem not to work

**Comment by Pacane** [comment]
Hmm, your last statement:

> the getLastError()call is not under an awaitcondition, so probably will not wait.

Is wrong. You don't need to `await` a returned statement.

Now I am not sure why the `collection.update()` doesn't work for you. Would you mind sharing your snippet demonstrating so?

**Comment by giorgiofran** [comment]
ASAP I'll try to provide an example.
I'm using mongo dart 0.2.9

**Comment by giorgiofran** [comment]
The following is an example:

```
import 'package:mongo_dart/mongo_dart.dart';

main() async {

  DbCollection      coll;
  List test = [1, 2, 3];
  String mongodbUri = '127.0.0.1';
  String database_name = 'await_test';
  Db db = new Db("mongodb://$mongodbUri:27017/$database_name");

  await db.open();
  coll = await db.collection('action');
  await coll.remove({});
  await coll.insert({'key': 1, 'incField' : 0});
  await coll.insert({'key': 2, 'step' : 0});

  for (int idx in test) {
    await process(idx, coll);
  }
}

process(int value, DbCollection coll) async {
  print('- Before adding $value');
  await coll.update({'key' : 1}, {r'$inc' : {'incField' : value}});
  print('- After $value added');
  addStep(coll);
}

addStep(DbCollection coll) async {
  Map result = await coll.findOne({'key' : 2});
  await coll.update({'_id' : result['_id']}, {r'$inc' : {'step' : 1}});
  print('** After step increment');
}
```
When I run this I have the following output:

> - Before adding 1
> - After 1 added
> - Before adding 2
> - After 2 added
> - Before adding 3
> ** After step increment
> - After 3 added
> ** After step increment
> ** After step increment

I did not expect to see an "After Step increment" between "Before adding 3" and "After 3 added".

You can also try to increment the numbers in the test list if you like.

If I add` await `to the  `addStep(coll);` statement everything seems to work fine.

But my use case is that I have to update some minor fields and I'd like to do it asynchronously.

**Comment by vadimtsushko** [comment]
`await addStep(coll);` would still be executed asynchronously. It just add garantee order of execution.

Async operations without await do not have any order of execution (at least you can not rely on it)
That's by design. (And that is just as I understand it)

**Comment by giorgiofran** [comment]
Probably I didn't get correctly how `await` works.
I thought it suspended the function, executed the future function called and then returned. Everything synchronously.
But reading better the documentation it seems that it is not like that.
The function is supended, the future is put in the event loop and the suspended function immediately after, so that, when the future executes, it is immediately resumed.
The point is that the future function is not executed immediately.
At least is what I understood now reading the documentation. 
Do you think that it is correct?

**Comment by vadimtsushko** [comment]
I do not try to understand all intricate machinery of async/await. 
It seems to me that for end-user there is one simlpe rule: when execution order is important, you should use `await`. 
You probaby coud do without `await` when just invoking some even handler or whatnot

**Comment by giorgiofran** [comment]
Ok, thanks, I close the issue.
