### ISSUE TITLE
Failing test

### ISSUE THREAD

**Issue by thosakwe** [mongo-dart/mongo_dart#115]
There's a single test failing: https://travis-ci.org/mongo-dart/mongo_dart/builds/272261767

Wondering what the cause is.

**Comment by Pacane** [comment]
I don't remember what is the DB used for the tests, but you should verify what version is effective. Between versions 2 and 3, they changed the default authentication scheme. Then we should make sure the correct scheme is used depending on the version of mongo that's being used.
