### ISSUE TITLE
Support for Flutter

### ISSUE THREAD

**Issue by joaquinrok** [mongo-dart/mongo_dart#121]
Would this work in Flutter? I guess compatibility for each platform storage options would need to be added?

**Comment by Pacane** [comment]
Mongo dart uses dart:io to communicate with MongoDB. So I'd expect this to work with Flutter already.

**Comment by stubborncoder** [comment]
I was trying this out as I need some geoquery features in my app and firestore does not support them yet, so I thought to take part of my db to mlab, and I don't think this is working, example:
- Simple Dart working just fine:

![image](https://user-images.githubusercontent.com/11727994/41511810-c0773a08-727e-11e8-9a9e-bd63ee873f04.png)

- Flutter project with same mongo URI:

![image](https://user-images.githubusercontent.com/11727994/41511846-499e0848-727f-11e8-9fb5-bd080e95f3d2.png)

**Comment by niceguy1** [comment]
im getting the same errors and im unable to fix this

**Comment by vadimtsushko** [comment]
Interesting, I thought these strong type related errors are gone. Current version builds without errors on Travis with dev-65, which is Dart2 only
Do you use last version of mongo_dart and Dart SDK ?

**Comment by niceguy1** [comment]
thanks for replying @vadimtsushko trying to fix this for a long time now...
i use mongo_dart 0.3.2, cannot use mongo_dart 0.3.3 because flutter uses dev.63
i tried changing flutter from beta channel to dev - but still it uses dart dev.63
no idea whats next

**Comment by niceguy1** [comment]
sure, ill try that and report back, thank you!

**Comment by niceguy1** [comment]
hi @vadimtsushko, i tried:

dependencies:
  mongo_dart: ^0.3.2
dependency_overrides:
  mongo_dart: '0.3.3'

and got:

Because mongo_dart >=0.3.3 depends on pool ^1.3.6 and every version of flutter_test from sdk depends on pool 1.3.5, mongo_dart >=0.3.3 is incompatible with flutter_test from sdk.
So, because testing_from_net depends on both flutter_test any from sdk and mongo_dart 0.3.3, version solving failed.

**Comment by vadimtsushko** [comment]
Apparently, yes

**Comment by niceguy1** [comment]
i ended up overriding a bit more:

```
dependency_overrides:
  mongo_dart: '0.3.3'
  pool: '1.3.6'
  path: '1.6.2'
  logging: '0.11.3+2'
  crypto: '2.0.6'
  collection: '1.14.11'
  mongo_dart_query: '0.3.2'
  bson: '0.3.2'
  fixnum: '0.10.8'
```
package get passed ok, but i still getting that error:

```
Syncing files to device Android SDK built for x86...
E/flutter ( 9487): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter ( 9487): MongoDB ConnectionException: connection closed.
E/flutter ( 9487): #0      _ConnectionManager._connect (file:///C:/src/flutter/.pub-cache/hosted/pub.flutter-io.cn/mongo_dart-0.3.2/lib/src/network/connection_manager.dart:25:38)
E/flutter ( 9487): <asynchronous suspension>
```

**Comment by vadimtsushko** [comment]
Sorry, I know nothing about Flutter, but looking at your stacktrace it seems, that you are still using mongo_dart 0.3.2
Maybe error is related to that fact (maybe not)

**Comment by niceguy1** [comment]
your right, i didnt noticed that
package get gave me this:

```
C:\src\flutter\bin\flutter.bat --no-color packages get
Running "flutter packages get" in testing_from_net...
! bson 0.3.2
! collection 1.14.11
! crypto 2.0.6
! cupertino_icons 0.1.2
! fixnum 0.10.8
! logging 0.11.3+2
! mongo_dart 0.3.3
! mongo_dart_query 0.3.2
! path 1.6.2
! pool 1.3.6
Process finished with exit code 0
```

**Comment by niceguy1** [comment]
@vadimtsushko i went through the same process again and it seems to use 0.3.3 now, same error
```
Launching lib\main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...
Resolving dependencies...
Running 'gradlew assembleDebug'...
Built build\app\outputs\apk\debug\app-debug.apk.
Installing build\app\outputs\apk\app.apk...
E/flutter (10779): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter (10779): MongoDB ConnectionException: connection closed.
E/flutter (10779): #0      _ConnectionManager._connect (file:///C:/src/flutter/.pub-cache/hosted/pub.flutter-io.cn/mongo_dart-0.3.3/lib/src/network/connection_manager.dart:25:38)
E/flutter (10779): <asynchronous suspension>
```
could you direct me where i could find a solution? maybe another forum?
thank you for your time

**Comment by vadimtsushko** [comment]
Hm. Have you tried some tests or samples with standard Dart sdk? Is that problem specific to Flutter?
Maybe something in your environment

I don't have any specific advise

**Comment by niceguy1** [comment]
didnt try dart standalone yet, 
quick question: can i build a mobile app with dart standalone? (using material etc same as flutter...)

**Comment by vadimtsushko** [comment]
> quick question: can i build a mobile app with dart standalone? (using material etc same as flutter...)
Don't think so. But I know nothing about mobile development.
I've suggested to try dart standalone to isolate probable cause of error. Do it really flutter related and not, for example some firewall blocking your access to mongodb database.

**Comment by niceguy1** [comment]
i thought the same thing, but then i used mongo shell without a vpn and it worked just fine
i tried posting in futter bug report just now, meanwhile i guess i could try dart standalone
will report back here if i come up with something related to dart
thanks @vadimtsushko for your patience

**Comment by niceguy1** [comment]
hi @vadimtsushko i got similar error with dart standalone:
```
Unhandled exception:
MongoDB ConnectionException: connection closed.
#0      _ConnectionManager._connect (file:///C:/Users/tom/AppData/Roaming/Pub/Cache/hosted/pub.flutter-io.cn/mongo_dart-0.3.3/lib/src/network/connection_manager.dart:25:38)
<asynchronous suspension>
```

**Comment by vadimtsushko** [comment]
So there are some problems in your setup, I think.

**Comment by stubborncoder** [comment]
So please I tried again this package with flutter after a while and this seems not to be working, I would recommend you to modify pub page to state that this only works for dart standalone, it will save a lot of frustration to people.

**Comment by thosakwe** [comment]
Are you sure? You said it “seems to not be working” without any error message, stack trace, or reproduction steps.

Without that information, there’s no way for us to fix any error you’re having...

**Comment by stubborncoder** [comment]
Hello @thosakwe, you're totally right sorry for being such a dick, well in fact I finally got it working, it seems that there is a namespace conflict with the material.dart library.

So in order to get this working with Widgets (Statefull and Stateless) you have to show only what you need:

![working](https://user-images.githubusercontent.com/11727994/50383820-6387b580-06bb-11e9-9cd4-a84e79a53555.PNG)

This wont work

![not_working](https://user-images.githubusercontent.com/11727994/50383826-9fbb1600-06bb-11e9-966d-d86798ba5ce5.PNG)

My apollogies.

**Comment by thosakwe** [comment]
Huh, that’s interesting. Thanks for pointing that out. You’ve cleared this
up for anyone else who runs into this issue in the future.

**Comment by thosakwe** [comment]
That being said, if I had to guess, I’d assume that both mongo_dart and
flutter/material export a class named “State”.

So you can also just `import 'package:mongo_dart/mongo_dart.dart' as mgo;`
