### ISSUE TITLE
Dart 2 Compatibility issue: 'Future<dynamic>' is not a subtype of type 'Future<bool>'

### ISSUE THREAD

**Issue by andrewlytics** [mongo-dart/mongo_dart#124]
Hello,

When using Dart2 on a flutter project with mongo_dart, the connect function is not working:

<img width="1179" alt="screen shot 2018-04-13 at 11 40 29 am" src="https://user-images.githubusercontent.com/8008340/38749677-b6858114-3f0f-11e8-9fff-459f86c21e40.png">

More details in this issue: flutter/flutter#15654

**Comment by arnoldparge** [comment]
Mongo_dart will need to update the code for latest flutter version.
[Check this](https://medium.com/flutter-io/https-medium-com-flutter-io-announcing-flutters-beta-2-c85ba1557d5e)

**Comment by branflake2267** [comment]
An explicit type cast is needed.

**Comment by mit-mit** [comment]
Looks like there is a PR for this here: https://github.com/mongo-dart/mongo_dart/pull/130
