### ISSUE TITLE
Support for Decimal128 type

### ISSUE THREAD

**Issue by kaede28** [mongo-dart/mongo_dart#135]
When I save a number that is bigger than a signed 64-bit integer, mongo_dart saves it on MongoDB as a 64-bit integer, which loses precision. 

Is there a way to save it as Decimal128 type on MongoDB?

**Comment by giorgiofran** [comment]
At present it is not possible because the Decimal representation in package BSON is missing.

**Comment by giorgiofran** [comment]
Implemented. Check last release. I close this bug, feel free to open a new issue if needed.
