### ISSUE TITLE
Cannot connec to url with mongodb+srv:// protocol

### ISSUE THREAD

**Issue by yelliver** [mongo-dart/mongo_dart#137]
When I use mongo Atlas hosting, and connect with above url, it shows error "Failed host lookup"

**Comment by sestegra** [comment]
Related issue #35

**Comment by kindlychung** [comment]
Is there a work around for this? Thanks!

**Comment by argz777** [comment]
If I use "mongodb+srv://", I get an invalid scheme error,
if I use "mongodb://", I get failed host lookup.

I am guessing there's still no solution for this?

**Comment by thosakwe** [comment]
@argz777 Post your error message + stack trace, I'll see what I can do.

**Comment by argz777** [comment]
@thosakwe 
**my code is run on visual studio with a plain dart code.**

```
main(List<String> arguments) async {
  var uri = "mongodb://:@valenzuelacluster-71vej.mongodb.net/test?retryWrites=true&w=majority";
  Db db = new Db(uri);
  await db.open();
}
```

**so if I try to connect using the mongodb+srv, this is the error below.**

Unhandled exception:
MongoDart Error: Invalid scheme in uri: mongodb+srv://:@valenzuelacluster-71vej.mongodb.net/test?retryWrites=true&w=majority mongodb+srv 
0      Db._parseUri (package:mongo_dart/src/database/db.dart:120:7)
1      Db.open.<anonymous closure>.<anonymous closure> (package:mongo_dart/src/database/db.dart:217:42)
2      List.forEach (dart:core-patch/growable_array.dart:283:8)
3      Db.open.<anonymous closure> (package:mongo_dart/src/database/db.dart:216:16)
4      new Future.sync (dart:async/future.dart:224:31)
5      Db.open (package:mongo_dart/src/database/db.dart:207:19)
6      main (file:///C:/Users/Zhang-Gaming/Desktop/Projects/dart_gov/bin/main.dart:8:12)
<asynchronous suspension>
7      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)






**and if I try it without the +srv, this is the error.**





Unhandled exception:
SocketException: Failed host lookup: 'valenzuelacluster-71vej.mongodb.net' (OS Error: No such host is known.
, errno = 11001)
0      _ConnectionManager._connect (package:mongo_dart/src/network/connection_manager.dart:23:5)
<asynchronous suspension>
1      _ConnectionManager.open.<anonymous closure> (package:mongo_dart/src/network/connection_manager.dart:58:14)
2      Future.forEach.<anonymous closure> (dart:async/future.dart:492:26)
3      Future.doWhile.<anonymous closure> (dart:async/future.dart:534:26)
4      _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
5      _RootZone.bindUnaryCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1353:26)
6      Future.doWhile (dart:async/future.dart:549:18)
7      Future.forEach (dart:async/future.dart:490:12)
8      _ConnectionManager.open (package:mongo_dart/src/network/connection_manager.dart:56:19)
9      Db.open.<anonymous closure> (package:mongo_dart/src/database/db.dart:220:33)
10     new Future.sync (dart:async/future.dart:224:31)
11     Db.open (package:mongo_dart/src/database/db.dart:207:19)
12     main (file:///C:/Users/Zhang-Gaming/Desktop/Projects/dart_gov/bin/main.dart:8:12)
<asynchronous suspension>
13     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

**Comment by tgercek** [comment]
As far as I'm aware, this library doesn't handle newer Mongo connection strings. You'll have to use Db.pool() and pass in a list of your replicas' URIs.

To get these from Atlas, got to 'Connect' -> 'Connect with Shell' -> 'I have the Mongo Shell installed' -> set your version to 3.4 or earlier.

If you have 3 replicas, you will have 3 URLs split up with commas.

To the Db.pool() command you'll have to pass in each of these URLs prefaced with `mongodb://`, followed by `/test?authSource=[your auth db (probably 'admin')]`.

Since Atlas now only allows SSL connections, you'll need the source from #147 to open a secure connection. I've just finished adding tests for this so hopefully will get it merged up soon.

**Comment by argz777** [comment]
okay, thank you for the help!

I'll try that out first.

**Comment by reidterror** [comment]
> As far as I'm aware, this library doesn't handle newer Mongo connection strings. You'll have to use Db.pool() and pass in a list of your replicas' URIs.
> 
> To get these from Atlas, got to 'Connect' -> 'Connect with Shell' -> 'I have the Mongo Shell installed' -> set your version to 3.4 or earlier.
> 
> If you have 3 replicas, you will have 3 URLs split up with commas.
> 
> To the Db.pool() command you'll have to pass in each of these URLs prefaced with `mongodb://`, followed by `/test?authSource=[your auth db (probably 'admin')]`.
> 
> Since Atlas now only allows SSL connections, you'll need the source from #147 to open a secure connection. I've just finished adding tests for this so hopefully will get it merged up soon.

here's an example

`Db db = new Db.pool([
      **"mongodb://<username>:<password>@<hostname1>:27017/<DBName>?ssl=true&replicaSet=<MySet>&authSource=admin&retryWrites=true&w=majority",**
      "mongodb://<username>:<password>@<hostname2>:27017/<DBName>?ssl=true&replicaSet=<MySet>&authSource=admin&retryWrites=true&w=majority",
      "mongodb://<username>:<password>@<hostname3>:27017/<DBName>?ssl=true&replicaSet=<MySet>&authSource=admin&retryWrites=true&w=majority"
    ]);`

**Comment by CircleOnCircles** [comment]
> > As far as I'm aware, this library doesn't handle newer Mongo connection strings. You'll have to use Db.pool() and pass in a list of your replicas' URIs.
> > To get these from Atlas, got to 'Connect' -> 'Connect with Shell' -> 'I have the Mongo Shell installed' -> set your version to 3.4 or earlier.
> > If you have 3 replicas, you will have 3 URLs split up with commas.
> > To the Db.pool() command you'll have to pass in each of these URLs prefaced with `mongodb://`, followed by `/test?authSource=[your auth db (probably 'admin')]`.
> > Since Atlas now only allows SSL connections, you'll need the source from #147 to open a secure connection. I've just finished adding tests for this so hopefully will get it merged up soon.
> 
> here's an example
> 
> ```
> Db db = new Db.pool([
>       "mongodb://<username>:<password>@<hostname1>:27017/<DBName>?ssl=true&replicaSet=<MySet>&authSource=admin&retryWrites=true&w=majority",
>       "mongodb://<username>:<password>@<hostname2>:27017/<DBName>?ssl=true&replicaSet=<MySet>&authSource=admin&retryWrites=true&w=majority",
>       "mongodb://<username>:<password>@<hostname3>:27017/<DBName>?ssl=true&replicaSet=<MySet>&authSource=admin&retryWrites=true&w=majority"
>     ]);
> ```

Follow by 
```dart
await db.open(secure: true);
```

**Comment by SPK-RPI** [comment]
`await db.open(secure: true);`

no parameter like secure

**Comment by CircleOnCircles** [comment]
> `await db.open(secure: true);`
> 
> no parameter like secure

you can checkout this https://github.com/mongo-dart/mongo_dart/pull/147

or
add this to your flutter app
```yaml
mongo_dart:
    git:
        url: "https://github.com/tgercek/mongo_dart.git
```

first.

**Comment by jaycreate** [comment]
> > > As far as I'm aware, this library doesn't handle newer Mongo connection strings. You'll have to use Db.pool() and pass in a list of your replicas' URIs.
> > > To get these from Atlas, got to 'Connect' -> 'Connect with Shell' -> 'I have the Mongo Shell installed' -> set your version to 3.4 or earlier.
> > > If you have 3 replicas, you will have 3 URLs split up with commas.
> > > To the Db.pool() command you'll have to pass in each of these URLs prefaced with `mongodb://`, followed by `/test?authSource=[your auth db (probably 'admin')]`.
> > > Since Atlas now only allows SSL connections, you'll need the source from #147 to open a secure connection. I've just finished adding tests for this so hopefully will get it merged up soon.
> > 
> > 
> > here's an example
> > ```
> > Db db = new Db.pool([
> >       "mongodb://<username>:<password>@<hostname1>:27017/<DBName>?ssl=true&replicaSet=<MySet>&authSource=admin&retryWrites=true&w=majority",
> >       "mongodb://<username>:<password>@<hostname2>:27017/<DBName>?ssl=true&replicaSet=<MySet>&authSource=admin&retryWrites=true&w=majority",
> >       "mongodb://<username>:<password>@<hostname3>:27017/<DBName>?ssl=true&replicaSet=<MySet>&authSource=admin&retryWrites=true&w=majority"
> >     ]);
> > ```
> 
> Follow by
> 
> ```dart
> await db.open(secure: true);
> ```

This solution is work for me, thanks @CircleOnCircles

**Comment by giorgiofran** [comment]
tgercek work have been merged into release 0.4.1.

**Comment by CircleOnCircles** [comment]
> tgercek work have been merged into release 0.4.1.

This issue should be closed then.

**Comment by giorgiofran** [comment]
I would keep it open because it is possible to connect to TLS secured databases (like Atlas), but still you have to specify a mongodb:// list of servers.

**Comment by giorgiofran** [comment]
Now also `mongodb+srv:// ` Urls are accepted from release 0.4.2 using the Db.create() constructor.
