### ISSUE TITLE
Implement insertOne

### ISSUE THREAD

**Issue by tejainece** [mongo-dart/mongo_dart#138]
Implement [insertOne](https://docs.mongodb.com/manual/reference/method/db.collection.insertOne/), so one can get the inserted id.

**Comment by vadimtsushko** [comment]
I think it is a duplicate of https://github.com/mongo-dart/mongo_dart/issues/62
Isn't it?

**Comment by tejainece** [comment]
Kinda like solution for it. Yes. Should we move this there?

**Comment by vadimtsushko** [comment]
Does not it help?
https://stackoverflow.com/questions/14186321/dart-mongodb-get-id-after-insert

**Comment by tejainece** [comment]
That is what I do now. Mongo's `insertOne` returns the auto insert id.

**Comment by giorgiofran** [comment]
insertOne has been implemented in last published pre-release (null-safety compliant).

**Comment by giorgiofran** [comment]
I close this issue, feel free to open a new one if needed.
