### ISSUE TITLE
Support db.eval(...)

### ISSUE THREAD

**Issue by MrCheater** [mongo-dart/mongo_dart#144]
The eval command evaluates JavaScript functions on the database server.
https://docs.mongodb.com/manual/reference/command/eval/

**Comment by giorgiofran** [comment]
We have no plans for this, because it has been deprecated.

> Remove Support for the eval Command
> Starting in version 4.2, MongoDB removes the eval command. eval command has been deprecated since version 3.0.
>  The associated MongoDB 4.2 mongo shell methods db.eval() and db.collection.copyTo() can only be run when connected to MongoDB 4.0 or earlier.
