### ISSUE TITLE
Connecting to databases with SSL/TLS

### ISSUE THREAD

**Issue by tgercek** [mongo-dart/mongo_dart#146]
Wondering if there is any planned support/any specific setbacks with relation to supporting SSL databases? Happy to contribute.

We're able to use this for databases hosted inside our own cluster, but we (and I've noticed some others) are unable to connect to databases through services like Atlas that force SSL/TLS.

**Comment by tgercek** [comment]
I've done work on this in #147.

**Comment by giorgiofran** [comment]
Merged, thanks.
