### ISSUE TITLE
Add Geo query

### ISSUE THREAD

**Issue by Jo-zTk** [mongo-dart/mongo_dart#151]
Hi,

Is there a way to perform Geo request using coordinates, radius and type like 'point' ?
Like with 'geoWithin' in mongodb ?

Thank

**Comment by gitdefllo** [comment]
What about using `near` with coordinates and a radius ?

---

Assuming you have a model of data with specific location coordinates:
```java
{
  ...
  'location': {
      'type': 'Point',
      'coordinates': ['latitude', 'longitude']
    }
}
```
You could get a range of near locations within a radius:
```dart
var _loc = {
  'type': 'Point',
  'coordinates': [x, y]
}

var result = [];
await collection
    .find(where.near('location', _loc, _radius))
    .forEach((data) {
   print(data);
   result.add(data);
});
```

Before doing it, you should create a 2dsphere index as follows:
```dart
await db.createIndex('collectionName', keys: {'location': '2dsphere'});
```
---
Could it be what you're looking for?

**Comment by giorgiofran** [comment]
I close this bug, feel free to open a new issue if needed.

**Comment by Farhan-hyd** [comment]
did anyone has idea how to import and use ShapeOperator instances: Box , Center, CenterSphere, Geometry and use them in geowithin
