### ISSUE TITLE
Supports uri with multiple hosts

### ISSUE THREAD

**Issue by pd4d10** [mongo-dart/mongo_dart#152]
For example:

```dart
var uri = 'mongodb://mongodb0.example.com:27017,mongodb1.example.com:27017,mongodb2.example.com:27017/admin?replicaSet=myRepl';
var db = Db(uri)
```

should be treated as connection pool.

Reference: [Mongodb documentation](https://docs.mongodb.com/manual/reference/connection-string/#standard-connection-string-format)

**Comment by giorgiofran** [comment]
Please, check release 0.4.1 and let me know.

**Comment by giorgiofran** [comment]
I close this issue, feel free to open a new one if needed.
