### ISSUE TITLE
v0.3.5  compiler error 

### ISSUE THREAD

**Issue by rambozzang** [mongo-dart/mongo_dart#156]
Hi, since the last version of dart ,   I have this error

file:///C:/Program%20Files/flutter/.pub-cache/hosted/pub.dartlang.org/mongo_dart-0.3.5/lib/src/network/connection.dart:60:48: Error: The argument type 'StreamTransformer<List<int>, MongoReplyMessage>' can't be assigned to the parameter type 'StreamTransformer<Uint8List, dynamic>'.
 - 'StreamTransformer' is from 'dart:async'.
 - 'List' is from 'dart:core'.
 - 'MongoReplyMessage' is from 'package:mongo_dart/mongo_dart.dart' ('file:///C:/Program%20Files/flutter/.pub-cache/hosted/pub.dartlang.org/mongo_dart-0.3.5/lib/mongo_dart.dart').
 - 'Uint8List' is from 'dart:typed_data'.
Try changing the type of the parameter, or casting the argument to 'StreamTransformer<Uint8List, dynamic>'.
          .transform(new MongoMessageHandler().transformer)

last line error . =>  MongoMessageHandler().  at dot

**Comment by rambozzang** [comment]
i solved Iby modifying the  mong_messange_dtransformer.dart

List<int> -> Uint8List
in mongo_message_transformer.dart

**Comment by Pacane** [comment]
can you PR your change? thank you.
Joel Trottier-Hebert
