### ISSUE TITLE
Add support for arrayFilters option

### ISSUE THREAD

**Issue by ryanheise** [mongo-dart/mongo_dart#157]
`collection.update()` does not support the `arrayFilters` option.

I've looked at the code, but it seems like a protocol-level thing so I probably won't be capable of making a pull request. Hence I'd like to submit it a feature request.

**Comment by Antoine-Assaf15** [comment]
Any news regarding this feature?

**Comment by jodinathan** [comment]
this should be fixed in https://github.com/mongo-dart/mongo_dart/pull/203

**Comment by giorgiofran** [comment]
A new null-safety pre-release has been published. It contains also the possibility of specifying array filters (using `modernUpdate` method)

**Comment by giorgiofran** [comment]
I close this issue, feel free to open a new one if needed.
