### ISSUE TITLE
ensureIndex InvalidNamespace error

### ISSUE THREAD

**Issue by samuelventura** [mongo-dart/mongo_dart#158]
Index creation in v0.3.5 is throwing me an exception on mongodb 4.2 on both Windows and Mac.

```dart
import 'package:mongo_dart/mongo_dart.dart';
var db = Db("mongodb://localhost:27017/someDatabase");
await db.open();
await db.ensureIndex("someCollection", key: "someField");

Unhandled exception:
{connectionId: 3, err: cannot write to 'someDatabase.system.indexes', code: 73, codeName: InvalidNamespace, n: 0, ok: 1.0}
#0      Db.ensureIndex (package:mongo_dart/src/database/db.dart:555:24)
<asynchronous suspension>
#1      main (file:///Users/someUser/someFile.dart:12:10)
<asynchronous suspension>
#2      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

**Comment by thumbert** [comment]
Confirm that the test  ```testIndexCreation()```   and ```testEnsureIndexWithIndexCreation()``` fail under Mongo 4.2 with 0.4.0-dev.1 on Ubuntu too.

dart:async                                      _Completer.completeError
package:mongo_dart/src/database/db.dart 249:14  Db.executeDbCommand
===== asynchronous gap ===========================
dart:async                                      _asyncThenWrapperHelper
package:mongo_dart/src/database/db.dart         Db.executeDbCommand
package:mongo_dart/src/database/db.dart 288:12  Db.getLastError
package:mongo_dart/src/database/db.dart 477:14  Db.createIndex.<fn>
===== asynchronous gap ===========================
dart:async                                      _asyncThenWrapperHelper
package:mongo_dart/src/database/db.dart         Db.createIndex.<fn>
dart:async                                      new Future.sync
package:mongo_dart/src/database/db.dart 447:19  Db.createIndex
package:mongo_dart/src/database/db.dart 518:30  Db.ensureIndex
===== asynchronous gap ===========================
dart:async                                      _asyncThenWrapperHelper
package:mongo_dart/src/database/db.dart         Db.ensureIndex
test/database_test.dart 927:16                  testEnsureIndexWithIndexCreation
===== asynchronous gap ===========================
dart:async                                      _asyncThenWrapperHelper
test/database_test.dart                         testEnsureIndexWithIndexCreation

{connectionId: 116, err: cannot write to 'test-mongo-dart.system.indexes', code: 73, codeName: InvalidNamespace, n: 0, ok: 1.0}

**Comment by giorgiofran** [comment]
Any new about this issue?

**Comment by giorgiofran** [comment]
Hi guys, I spent my Christmas holidays working on this issue. 
Now I have a working environment, but, before creating a pull request, I'd like to test my work more extensively. At present I'm only testing on a single server.
I'd need someone testing also on a replica and sharded environment (I have no more time to do that ... :-( ).
I estimate that I should be able to upload on GitHub my project this week-end.
Anyone interested?

**Comment by giorgiofran** [comment]
I have created a pull request.

**Comment by thumbert** [comment]
Thanks giorgiofran!   

Can someone take a look and merge this pull request?  Thank you very much.

**Comment by giorgiofran** [comment]
Fix available now as pre-release in pub.
