### ISSUE TITLE
isConnected() method?

### ISSUE THREAD

**Issue by isaacgg** [mongo-dart/mongo_dart#167]
Hello, is there any way to find out if I'm currently connected to my DB?

**Comment by gitdefllo** [comment]
`Db` has a [`state` object](https://github.com/mongo-dart/mongo_dart/blob/c86a68cf9ed330e90a67845a2738ac7369bc4611/lib/src/database/state.dart), use it to know if you're currently connected to db:  `db.state == State.OPEN`

**Comment by tomrozb** [comment]
In my case the state is OPEN but I'm not longer connected to the database. Is it a known issue? Looks like even if connection is lost this state is not changed, and currently there's no way to check if you are connected or not. I'm running the application on Android and in most cases the app gets disconnected when your app goes into background. When you navigate back to the app, the state is OPEN but really the connection is closed.

**Comment by giorgiofran** [comment]
There was a problem with the state update. I did some changes. May you please try with the last release and let me know if it is OK?

**Comment by giorgiofran** [comment]
I have created an `isConnected` getter in the `Db` class. I hope that it can help. It returns true if the Database state is `OPEN` and at least the primary connection is connected. I close the issue, feel free to reopen it for any other question.
