### ISSUE TITLE
flutter problem of connection with mongodb

### ISSUE THREAD

**Issue by panda-dev111** [mongo-dart/mongo_dart#170]
im trying to connect with mongodb using mongodb packages but i have this problem
also im trying to connect with port 27017 but every hot restart i get a random port
![problem](https://user-images.githubusercontent.com/58141263/69496309-161a5680-0ed1-11ea-942a-6c3517acea18.PNG)
![function](https://user-images.githubusercontent.com/58141263/69496310-1adf0a80-0ed1-11ea-927a-29cfcf16c3af.PNG)

**Comment by SPK-RPI** [comment]
Facing the same issue

**Comment by panda-dev111** [comment]
just open port  27017  in firewall

Le mar. 17 mars 2020 à 04:46, Shiba Prasad Kar <notifications@github.com> a
écrit :
