### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by ericklopez3** [mongo-dart/mongo_dart#175]
@thosakwe block isn't a solution. Here I'm again.

At first I really thought such a good project had died. You have no public members and I didn't know how to get an answer, so I asked in the PRs. I also keep open source projects, and I know it's not easy to have time for everything. But sad to see more censorious attitudes, I didn't offend anyone, just your ego by asking if the project was alive. Anyway, it was for a side project and it's good not to have to use this library.

**Comment by thosakwe** [comment]
From now on, further trolling will be blocked without a response.
