### ISSUE TITLE
why not like JS

### ISSUE THREAD

**Issue by note8g2018** [mongo-dart/mongo_dart#179]
I see many mongodb driver API and find the dart is the hardest to use. so why you do not do it like node.js Driver. I think it the most easy one to use. 
please improve it like Node.js driver.
and there is no good documentation for dart while node.js has a good documentation 
others ways I will quiet Flutter and move to reactNative even JS is the worst language ever.
😭😭😭😥😥😥

**Comment by thosakwe** [comment]
Sounds like a great opportunity for you to send in a pull request ;)

What specifically would you like to see improved? We can figure out how to get it rolling.

**Comment by note8g2018** [comment]
I do not know how to pull request.
for example, Projection in dart is very hard and need pipline not like in node.js which is very easy.
also in node.js id is auto created not like in dart you should created.
also, when I insertOne() should return the documents with id or at least the id.
and I hop you do good youtube tutorial that use most method in API.
then I will be like this 😁but now I like this  😢
finally, as great Billie Eilish said make it easy type.

**Comment by giorgiofran** [comment]
Please, check lats improvements. I close this bug, feel free to open a new issue if needed.
