### ISSUE TITLE
Flutter don't compile

### ISSUE THREAD

**Issue by josinei-br** [mongo-dart/mongo_dart#182]
I made app with flutter and mongodb app for teaching but it doesn't compile.
I can compile with no reference to mongo_dart, but when i include these line:

import 'package:mongo_dart/mongo_dart.dart' show Db;

or 

import 'package:mongo_dart/mongo_dart.dart' as mongo;

The app stop compiling.
Running Gradle task 'assembleDebug'... 
Contunues forever. No error message, no response, just wait forever for finish.

I not even using Db ou any other class from mongo_dart just to test. Only adding the import statement and stop compiling.

Dependencies on pubspec.yaml:

dependencies:
  flutter:
    sdk: flutter
  mongo_dart: ^0.3.6
  preferences: ^5.1.0

Thanks for any help.

Josinei

**Comment by teerasej** [comment]
Hi, I don't sure about what you are doing. But I assume that you are using this package in mobile application, aren't you? 

This package's goal seem to settle on server-side, not client-side or mobile application. So I don't think it will work in Flutter project. 

If you are looking for implementation of NoSQL-like on mobile application, try [Sembast](https://pub.dev/packages/sembast) I used its in almost project I worked.

**Comment by josinei-br** [comment]
Thenks for your answer.

I'm teaching mobile computing and i wrote some examples about persistence.
Some about direct acces to postgresql and mysql, onre about firebase and
another about access by a REST web service

My intention was to add one about direct access ta MongoDB. But i cant
because the plugin don t work with flutter.

Thanks

Josinei

Em dom., 14 de jun. de 2020 às 02:04, Teerasej Jiraphatchandej <
notifications@github.com> escreveu:

**Comment by giorgiofran** [comment]
It does not work with flutter/web, but flutter/android or flutter/IOS should be fine.
In general, mongo_dart is not compatible with dart:html, so, if dart:io is used, it should work.

**Comment by josinei-br** [comment]
Thanks for your awser

Em seg, 24 de ago de 2020 12:59, Giorgio <notifications@github.com>
escreveu:

**Comment by giorgiofran** [comment]
Welcome
