### ISSUE TITLE
How to implement the Text-Search in mongo_dart, I was following mongodb documentation, mongo_dart is different than actual MongoDb implementation.

### ISSUE THREAD

**Issue by SaiVaraPrasad-3** [mongo-dart/mongo_dart#185]
**Like how to implement this:**
`db.stores.createIndex( { name: "text", description: "text" } )`
`db.stores.find( { $text: { $search: "java coffee shop" } } )`

**Mongodb text search documentation:**
### https://docs.mongodb.com/manual/text-search/

**It would be great, if someone provides documentation for mongo_dart package**

**Comment by SaiVaraPrasad-3** [comment]
### Actual mongodb documentation:
https://docs.mongodb.com/manual/text-search/

**Comment by giorgiofran** [comment]
`var db = Db('<Your Uri String>');`
`await db.open();`
`var coll = db.collection('<your collection name>');`

`await coll.insertAll(<your data>); `
Example `await coll.insertAll( [{'_id': 1, 'name': 'Java Hut', 'description': 'Coffee and cakes'},
    {'_id': 2, 'name': 'Burger Buns', 'description': 'Gourmet hamburgers'}]);`

`await coll.createIndex(keys: {<your fields>}); `
Example `await coll.createIndex(keys: {'name': 'text', 'description': 'text'});`

`var result = await collection.find({ r'$text': {r'$search': '<your search words>'}}).toList();` 
Example  `var result = await collection.find({ r'$text': {r'$search': 'java coffee shop'}}).toList();`

**Comment by giorgiofran** [comment]
I close this bug, feel free to open a new issue if needed.
