### ISSUE TITLE
Work with Bulk operations

### ISSUE THREAD

**Issue by levichevdmitry** [mongo-dart/mongo_dart#186]
Hello, guys. Anybody can help me how  to create not ordered bulk operations and execute they then?

**Comment by giorgiofran** [comment]
I'm sorry, but there is no bulk support yet.

**Comment by giorgiofran** [comment]
A new development release have been published. It contains many improvements, among others, watch(), bulkWrite() (partial...) and Decimal 128. If you can, please, give it a try and report bugs and suggestions.

**Comment by giorgiofran** [comment]
Also a null-safety pre-release has been published. I close this bug, feel free to open a new issue if needed.
