### ISSUE TITLE
not connecting to atlas urls

### ISSUE THREAD

**Issue by ShadowGits** [mongo-dart/mongo_dart#195]

**Comment by giorgiofran** [comment]
Can you provide more detailed info?

**Comment by Ayush412** [comment]
> Can you provide more detailed info?
Hello Sir,
Current atlas URIs look like: mongodb+srv://<user>:<password>@<host>/<database-name>?<parameters>
URI as per mongo_dart docs: mongodb+srv://<user>:<password>@<host>:**<port>**/<database-name>?<parameters>

The 'port' is not provided by atlas with the generated URI.
If I am missing something and haven't understood the documentation properly, kindly correct me. I am new to mongodb.

**Comment by giorgiofran** [comment]
This is typical way to  open a connection with Atlas:
```
var db = await Db.create("mongodb+srv://<user>:<password>@<host>:<port>/<database>?<parameters>");
await db.open();
```
Also in my experience the port is missing in Atlas uri.
Which is the error you get?

**Comment by ShadowGits** [comment]
Sorry for the delay.

Error: MongoDB ConnectionException: Could not connect to the Data Base.
This is the error, although i have like tripled checked the parameters, and when used with local mongo db, it works fine.
Also as you mentioned the missing port in Atlas URI. Any workaround to it ?

**Comment by Ayush412** [comment]
The uri provided by atlas works perfectly fine for me with `Db.create()` even though the port isn't provided. 

I was facing the same issue initially, but I had forgotten to **whitelist the IP address** of the device accessing my cluster. That fixed the connection issue. This can be done under "Network Access".

If you wish to provide access to all devices on the internet rather than manually entering each, whitelist 0.0.0.0/0. (Not recommended)

**Comment by ShadowGits** [comment]
Hey, Ayush can you paste here the exact code snippet here. I have already been trying with IP Adress whitelisiting as 0.0.0.0/0 yet it throws an exception

**Comment by ShadowGits** [comment]
> The uri provided by atlas works perfectly fine for me with `Db.create()` even though the port isn't provided.
> 
> I was facing the same issue initially, but I had forgotten to **whitelist the IP address** of the device accessing my cluster. That fixed the connection issue. This can be done under "Network Access".
> 
> If you wish to provide access to all devices on the internet rather than manually entering each, whitelist 0.0.0.0/0. (Not recommended)
