### ISSUE TITLE
Flutter Streambuilder

### ISSUE THREAD

**Issue by dhruv866** [mongo-dart/mongo_dart#197]
Is there any function that helps in building flutter streambuilder and provide realtime changes
If yes pls do reply....

**Comment by giorgiofran** [comment]
Unfortunately there is nothing about streambuilder and there is not any function that provides realtime changes.

**Comment by dhruv866** [comment]
Will it be coming in future

**Comment by giorgiofran** [comment]
About streambuilder, I believe nothing will be done if not in the long run.
With relation to changeStream(watch method), I see that it is an highly requested feature. I will investigate further to see if it is feasible in a reasonable amount of time and then I'll be able to respond to your question. Anyway, do not aspect any solution in the short/middle term.

**Comment by dhruv866** [comment]
Ok and thanks for giving your time 🙂

**Comment by giorgiofran** [comment]
The watch method (changeStream) has been implemented in the last release. I close this bug, feel free to open a new issue if needed.
