### ISSUE TITLE
read data without objectid in dart

### ISSUE THREAD

**Issue by imtiaz791** [mongo-dart/mongo_dart#199]
Hi,
Anybody can help me how to read data from mongodb without objectid in dart.

**Comment by giorgiofran** [comment]
Sorry, I couldn't get your question. What do you mean with "read data without ObjectId"? Can you give an example?

**Comment by tamereratik** [comment]
DART => a= coll.find().tolist  //result {_id:ObjectId("507c7f79bcf86cd7994f6c0e", "name":"some")}
b=a[0]["_id"] //result ObjectId("507c7f79bcf86cd7994f6c0e")

then i try b.id //result Bson("507c7f79bcf86cd7994f6c0e")
but we need only  "507c7f79bcf86cd7994f6c0e"

MONGO=> ObjectId("507c7f79bcf86cd7994f6c0e").valueOf() //result "507c7f79bcf86cd7994f6c0e"
or
ObjectId("507f191e810c19729de860ea").str //result "507c7f79bcf86cd7994f6c0e"

**Comment by giorgiofran** [comment]
Do you mean `b.toHexString()`?

**Comment by tamereratik** [comment]
yep.. can you put a shortcode like a.oid  //result "507c7f79bcf86cd7994f6c0e

**Comment by giorgiofran** [comment]
We can introduce a getter like the one you suggest in the `ObjectId` class. But not immediately. It will be available with the null-safety version. In the meanwhile you could create an `extension`.

**Comment by giorgiofran** [comment]
A null-safety pre-release has been published. The ObjectId class contains a new getter named "$oid" that does what you asekd. In a few words, `objectId.$oid == objectId.toHexString()`

**Comment by giorgiofran** [comment]
I'm closing this issue, feel free to re-open if needed.
