### ISSUE TITLE
Add watch function to listen the collection changes.

### ISSUE THREAD

**Issue by developershafeek** [mongo-dart/mongo_dart#208]

**Comment by giorgiofran** [comment]
Duplicate of #192

**Comment by giorgiofran** [comment]
A new development release have been published. It contains many improvements, among others, watch(), bulkWrite() (partial...) and Decimal 128. If you can, please, give it a try and report bugs and suggestions.

**Comment by giorgiofran** [comment]
Final release has landed. I close this issue.
