### ISSUE TITLE
What is the api level?

### ISSUE THREAD

**Issue by meridorkobi** [mongo-dart/mongo_dart#211]

**Comment by giorgiofran** [comment]
What do you mean exactly with "Api Level"?

**Comment by meridorkobi** [comment]
hello
Can I use this interface in my app and excecute on Android 8?
Thanks
Kobi

**Comment by giorgiofran** [comment]
I guess you can. I'm not a flutter expert, but I believe that you have to consider only the SDK level in order to use this package.

**Comment by giorgiofran** [comment]
I close this bug, feel free to open a new issue if needed.
