### ISSUE TITLE
Expect type binData but found string., code: 2, codeName: BadValue

### ISSUE THREAD

**Issue by AlienEngineer** [mongo-dart/mongo_dart#212]
using `DB("mongodb://<user>:<password>@<host>:<port>/some_db?ssl=true")` fails to connect with the error: `Expect type binData but found string., code: 2, codeName: BadValue`

Any ideas? Already connected successfully with other tools. e.g. Rider.

thanks in advance!

**Comment by AlienEngineer** [comment]
After debugging the driver, we have found that it's an issue on `db.authenticate(...)` looking into the `serverConfig` variable and it does look good.

**Comment by giorgiofran** [comment]
Hi,
  I tried to replicate the case, but I could not get those errors,  may you please give me more info?
- Which is the MongoDb version? 
- Is stand-alone, replica set or sharded cluster?
- Which version of the mongo_dart driver are you using?
- If it is not the last version, could you try it?
- Could you post the stack trace also?
- Do you have a snippet of code to reproduce the case?

Thanks in advance.

**Comment by AlienEngineer** [comment]
hi @giorgiofran, thanks for the quick reply. 

After your response, we tried with pre-release 0.5.0-dev.2 and the connection now worked perfectly. 

Unfortunately, the query returns an error:  "unknown operator: $query"

MongoDb v3.6.

**Comment by giorgiofran** [comment]
Can you send a snippet on how you are doing the query call?

**Comment by giorgiofran** [comment]
Beware if you are using the aggregate framework, because the stages requires the row map of the filter, so, if you use the `SelectorBuilder`, you have to write the stage like this:  
`.addStage( Match(where.eq('status', 'A').map['\$query']))`
(Example taken from the Readme file)

**Comment by AlienEngineer** [comment]
Hi @giorgiofran,

we are using https://github.com/bytedance/unpub/tree/master/unpub we had it working locally with a MongoDB docker image v3.2

**Comment by giorgiofran** [comment]
Can you give more info? A stack trace?
Are you using MongoDb 3.6 or 3.2?
I have seen that unpub uses an old version of the mongo_dart driver: `mongo_dart: ^0.3.6`

**Comment by AlienEngineer** [comment]
We've switched unpub dependency to use the latest pre-release. We are using MongoDB 3.6.

**Comment by giorgiofran** [comment]
I you want me to help you, I need more info.
I even tried to download unpub, changed the mongo_dart dependency to 0.5.0-dev.2,
upload a package to the local server, use it in another package without any problem.
Which query returns the error? How can I reproduce the case?
Is there any stack trace?

**Comment by AlienEngineer** [comment]
Hi @giorgiofran, sorry for the lack of feedback. The team was able to figure it out using the new pre-release version and switching up a few calls.
