### ISSUE TITLE
Do I need to sanitize my user inputs to avoid injection attacks, or does the lib handle that internally?

### ISSUE THREAD

**Issue by KOGI** [mongo-dart/mongo_dart#215]
I don't see any sort of parameterization or sanitization methods exposed or documented. Does the lib handle this internally, or do I need to do it myself before passing off to the lib?

**Comment by giorgiofran** [comment]
This is an interesting question. There no sanitization method in this package.
I guess that Dart, as a compiled strong type checked language, is quite safe, provided that you check the type of the parameter that you receive. I couldn't find any example of injection that could work in Dart (this does not mean that it does not exist).
Anyway, a basic control on the user input is always a good practice.

This said, there are some functions that can execute JavaScript code. These are potentially dangerous.
Please give a look to [this FAQ](https://docs.mongodb.com/manual/faq/fundamentals/#how-does-mongodb-address-sql-or-query-injection).

**Comment by KOGI** [comment]
Ah, this is a very good point. As long as string values are never parsed/expanded into maps/jsonObjects, there's no chance for injection to actually get evaluated.

Thanks for the clarity!

**Comment by giorgiofran** [comment]
Closing this issue. Feel free to ask for any other question you could have.
