### ISSUE TITLE
Dart 2.12.0 - Erro in implement 

### ISSUE THREAD

**Issue by Vluameiro** [mongo-dart/mongo_dart#216]
Hello guys, I'm having trouble implementing mongoDB in the new Dart.

Error below:

Attempt: 18 waiting for isolate dartdev to check in

**Comment by giorgiofran** [comment]
Mongo_dart has not yet a null-safety version. 
You can use a null-safety project inside a non null-safety one, but I guess you cannot do the opposite.
The message you receive is quite strange, when does it happen?

**Comment by Vluameiro** [comment]
Thank you very much for the feedback, Do you have any prediction for when the version for the new Dart will be released?
________________________________
De: Giorgio <notifications@github.com>
Enviado: 8 de março de 2021 13:34
Para: mongo-dart/mongo_dart <mongo_dart@noreply.github.com>
Cc: Vluameiro <valdimiro.luameiro@hotmail.com>; Author <author@noreply.github.com>
Assunto: Re: [mongo-dart/mongo_dart] Dart 2.12.0 - Erro in implement (#216)


Mongo_dart has not yet a null-safety version.
You can use a null-safety project inside a non null-safety one, but I guess you cannot do the opposite.
The message you receive is quite strange, when does it happen?

**Comment by giorgiofran** [comment]
I have first to make a stable release of the last OP_MSG changes (It should not take so much, but consider that I can work on this project only in the weekends). Then we have to wait that all the dependencies are ported to null-safety. Only at this point we can do the porting. I hope in one month to have at least a dev version.

**Comment by Vluameiro** [comment]
Thank you very much for the tip, but as soon as it is available, please give me feedback.
________________________________
De: Giorgio <notifications@github.com>
Enviado: 9 de março de 2021 10:33
Para: mongo-dart/mongo_dart <mongo_dart@noreply.github.com>
Cc: Vluameiro <valdimiro.luameiro@hotmail.com>; Author <author@noreply.github.com>
Assunto: Re: [mongo-dart/mongo_dart] Dart 2.12.0 - Erro in implement (#216)


I have first to make a stable release of the last OP_MSG changes (It should not take so much, but consider that I can work on this project only in the weekends). Then we have to wait that all the dependencies are ported to null-safety. Only at this point we can do the porting. I hope in one month to have at least a dev version.

**Comment by giorgiofran** [comment]
If you want to test a pre-development release you can do it temporarily using a git reference in your pubspec.yaml:

dependencies:
  mongo_dart:
    git: 
      url: https://github.com/mongo-dart/mongo_dart.git
      ref: null-safety

Note: all tests have been passed, but, in some aspects, null-safety is tricky. Maybe some unexpected error can happen.

**Comment by giorgiofran** [comment]
A null-safety pre-release has been published. I close this bug, feel free to open a new issue if needed.

**Comment by Vluameiro** [comment]
tank you for help.
________________________________
De: Giorgio ***@***.***>
Enviado: 1 de abril de 2021 17:13
Para: mongo-dart/mongo_dart ***@***.***>
Cc: Vluameiro ***@***.***>; Author ***@***.***>
Assunto: Re: [mongo-dart/mongo_dart] Dart 2.12.0 - Erro in implement (#216)


A null-safety pre-release has been published. I close this bug, feel free to open a new issue if needed.
