### ISSUE TITLE
package conflict

### ISSUE THREAD

**Issue by ChungTau** [mongo-dart/mongo_dart#217]
Because basic_utils >=2.7.0-rc.5 <3.0.0-nullsafety.0 depends on http ^0.12.2 and basic_utils >=1.0.5 <2.7.0-rc.5 depends on http ^0.12.0, basic_utils >=1.0.5 <3.0.0-nullsafety.0 requires http ^0.12.0.
And because mongo_dart >=0.4.2 depends on basic_utils ^2.6.2, mongo_dart >=0.4.2 requires http ^0.12.0.
And because firebase_storage >=8.0.0 depends on firebase_storage_web ^1.0.0 which depends on http ^0.13.0, mongo_dart >=0.4.2 is incompatible with firebase_storage >=8.0.0.
So, because hikeloca depends on both firebase_storage ^8.0.0 and mongo_dart ^0.4.4, version solving failed. 

flutter2.0

**Comment by ChungTau** [comment]
use mongo_dart ^0.4.1 can solve this problem but no change stream method in 0.4.1 version

**Comment by giorgiofran** [comment]
A null-safety version is not ready yet. Also version 0.4.2 does not contain a watch method.
For a watch method you have to use a 0.5.0-dev.3 release.
But you will have the same incompatibility.

**Comment by ChungTau** [comment]
Thanks a lot.

**Comment by giorgiofran** [comment]
A null-safety pre-release has been published. I close this bug, feel free to open a new issue if needed.
