### ISSUE TITLE
Please update your dependencies

### ISSUE THREAD

**Issue by fabiankaraben** [mongo-dart/mongo_dart#222]
Several packages have conflicts, with messages as:

> depends on crypto ^3.0.0 and mongo_dart >=0.4.1-dev.2.2 depends on crypto ^2.1.5

Please update your dependencies, specially crypto package.

Thanks for your wonderful work!

**Comment by giorgiofran** [comment]
Unfortunately, between the dependencies that use `crypto`, there is one that is still a pre-release.
For this reason I have updated the dependencies, but I could not create a _stable_ version. The release name is 0.5.1-rc.1.
You will have to change you pubspec in order to get this version.

**Comment by giorgiofran** [comment]
Also a null-safety pre-release have been published. I close this bug, feel free to open a new issue if needed.
