### ISSUE TITLE
db is in the wrong state: state.opening

### ISSUE THREAD

**Issue by meridorkobi** [mongo-dart/mongo_dart#223]
Hi, 
What is the reason?
What can I do to open without error?

**Comment by giorgiofran** [comment]
I'd need more info.
At least the mongo_dart version, but also the MongoDb release.
If you have also a snippet of code that are you using it would be helpful.

Did you await the call to db.open()?
```dart
db = Db('mongodb://127.0.0.1/testdb');
await db.open();
```

**Comment by meridorkobi** [comment]
Hi,
Its mobile app.

***MongoDb  -Atlas
***mongo_dart  - 
  mongo_dart:
    dependency: "direct main"
    description:
      name: mongo_dart
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.5.0+1"
  mongo_dart_query:
    dependency: transitive
    description:
      name: mongo_dart_query
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.4.2"


**Can I open and connect the DB and use the connection for all the time the app running in front or back, and change collections ?
how can I verify that connection is OK?   
  
**Code- attached
[DB.txt](https://github.com/mongo-dart/mongo_dart/files/6252087/DB.txt)

** The first version was without all the retries - until 
    print ("DBSTATUSI0" + _db.isConnected.toString()+ _db.state.toString());

Thanks Kobi

**Comment by giorgiofran** [comment]
If you look at the example/manual folder in the sources, you can get good examples.
The Db constructor simply prepares the internal data. So you do not need to await it, unless you use Db.create(), that is needed to connect with the mongodb+srv:// connection string.
Anyway, the real connection only happens in db.open().
Before of db.open it makes no sense to check the state.
If you want to be sure that the connection is open you can check the state calling db.isConnected.

Unfortunately mongo_dart, at present, does not try to automatically reconnect, so you have to do it manually if any problem occurs in your database. Even a member election, if you use a replica set, can cause a disconnection, because mongo_dart is always using the primary member.
This is a point that we have to improve in the next future.

**Comment by meridorkobi** [comment]
Thanks, it works properly.
But while debugging with a flutter started sometimes in the wrong condition, there may be residue from the previous time. Do you have an idea how to clean at the beginning?

**Comment by giorgiofran** [comment]
What do you mean with "residue"?

**Comment by meridorkobi** [comment]
In this situation I can not open the DB and have to restart again. 
This happens after repair and immediate running

**Comment by giorgiofran** [comment]
Can you give an example? Which is the situation?  What do you mean with "restart again"?
What do you mean with "repair" and "immediate running"?

**Comment by meridorkobi** [comment]
The app starts with automatic login or login or registration directly through mongodb.
Sometimes the process stacked because the state is not open.
This happens with the Android mobile phone, I have to try to login until success.
Maybe I need to start  with command to clear the connection.
Attach the new code.
Kobe


  mongo_dart:
    dependency: "direct main"
    description:
      name: mongo_dart
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.7.0-nullsafety.3"
  mongo_dart_query:
    dependency: transitive
    description:
      name: mongo_dart_query
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.1"
[DB.txt](https://github.com/mongo-dart/mongo_dart/files/6259504/DB.txt)

**Comment by giorgiofran** [comment]
It is not clear to me what do you mean with  " automatic login or login or registration directly through mongodb."
Anyway, I have prepared a simple class inspired from what you did.
Try to use it and tell me if it works.
```dart
import 'package:mongo_dart/mongo_dart.dart';

const dbName = 'mongo-dart-example';
const dbAddress = '127.0.0.1';

void main() async {
  var db = await connection.db;

  if (!db.masterConnection.serverCapabilities.supportsOpMsg) {
    return;
  }

  var collectionName = 'delete-many';
  await db.dropCollection(collectionName);
  var collection = db.collection(collectionName);

  var ret = await collection.insertMany([
    {'_id': 3, 'name': 'John', 'age': 32},
    {'_id': 4, 'name': 'Mira', 'age': 27},
    {'_id': 7, 'name': 'Luis', 'age': 42},
  ]);
  if (!ret.isSuccess) {
    print('Error detected in record insertion');
  }

  var res = await collection.deleteMany(where.lt('age', 40));

  print('Removed documents: ${res.nRemoved}'); // 2

  var findResult = await collection.find().toList();

  print('First record name: ${findResult.first['name']}'); // 'Luis';

  await connection.close();
}

DbConnection connection = DbConnection._(dbAddress, '27017', dbName);

class DbConnection {
  DbConnection._(this.host, this.port, this.dbName);
  final String host;
  final String port;
  final String dbName;

  String get connectionString => 'mongodb://$host:$port/$dbName';

  int retryAttempts = 5;

  static bool started = false;

  Db? _db;
  Future<Db> get db async => getConnection();

  Future<void> close() async {
    if (_db != null) {
      await _db!.close();
    }
  }

  Future<Db> getConnection() async {
    if (_db == null || !_db!.isConnected) {
      await close();
      var retry = 0;
      while (true) {
        try {
          retry++;
          var db = Db(connectionString);
          await db.open();
          _db = db;
          print('OK after "$retry" attempts');
          break;
        } catch (e) {
          if (retryAttempts < retry) {
            print('Exiting after "$retry" attempts');
            rethrow;
          }
          // each time waits a little bit more before re-trying
          await Future.delayed(Duration(milliseconds: 100 * retry));
        }
      }
    }
    return _db!;
  }
}

```

**Comment by giorgiofran** [comment]
I close this issue, feel free to open a new one if needed.

**Comment by meridorkobi** [comment]
Its working correctly!
I changed the process to the following and called the getDB() at the begging of the app before widgets started to work

class DB {
  static Db _db = null;
  static String _getConnectionString() {
    return "mongodb://XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX   
  }
  static Future <Db> getDB() async {
    try {
      if (_db == null) {
        _db = await Db(_getConnectionString());
        await _db.open();
      }
      if (_db != null && _db.isConnected && _db.state == State.OPEN) {
        return _db;
      }
      await _db.close();
      await _db.open();
      if (_db != null && _db.isConnected && _db.state == State.OPEN) {
        return _db;
      }
    } catch (e) {
      print(e);
    }
    return null;
  }

**Comment by Hu-Wentao** [comment]
> 

it work for me!

```dart
import 'package:mongo_dart/mongo_dart.dart';

class MongoAuthBasic {
  final String username;
  final String password;

  const MongoAuthBasic({required this.username, required this.password});

  toAuthPreString() => "$username:$password@";
}

class MongoStorageConfig {
  final MongoAuthBasic? auth;
  final String host;
  final int port;
  final String databaseName;
  final String authSource;
  final int retryAttempts;

  MongoStorageConfig({
    this.auth,
    this.host = "localhost",
    this.port = 27017,
    required this.databaseName,
    this.authSource = "admin",
    this.retryAttempts = 5,
  });

  String get authStr => auth?.toAuthPreString() ?? "";

  String fullUri() =>
      'mongodb://$authStr$host:$port/$databaseName?authSource=$authSource';
}

// 一个Storage表示一个数据库, 因此不需要泛型约束
abstract class IMongoStorage {
  MongoStorageConfig get config; // 配置一个mongo database的信息

  Db? _db;

  Db get syncDb =>
      _db ??
      (throw "Please use [await $runtimeType::preInit()] to init Storage");

  /// see [withSyncBox] [withSyncAsync]
  Future<Db> get asyncDb async {
    _db ??= await preInit();
    return _db!;
  }

  Future<void> close() async => await _db?.close();

  /// 如果在依赖注入时调用本方法,则可以使用 sync相关方法
  /// see: https://github.com/mongo-dart/mongo_dart/issues/223#issuecomment-813872280
  Future<Db> preInit() async {
    if (_db == null || !_db!.isConnected) {
      await close();
      var retry = 0;
      while (true) {
        try {
          retry++;
          var db = Db(config.fullUri());
          await db.open();
          _db = db;
          // print('OK after "$retry" attempts');
          break;
        } catch (e) {
          if (retry >= config.retryAttempts) {
            // print('Exiting after "$retry" attempts');
            rethrow;
          }
          // each time waits a little bit more before re-trying
          await Future.delayed(Duration(milliseconds: 100 * retry));
        }
      }
    }
    return _db!;
  }

  /// 在实现类内部创建 静态inject方法,内部调用本方法即可实现无@module, @preResolve注入
  Future<T> init<T extends IMongoStorage>() async {
    await preInit();
    return this as T;
  }

  Future<E> withSync<E>(E Function(Db sync) onSync) async =>
      onSync(await asyncDb);

  Future<E> withSyncAsync<E>(Future<E> Function(Db sync) onSync) async =>
      await onSync(await asyncDb);
}

class BaseMongoStorage extends IMongoStorage {
  @override
  final MongoStorageConfig config;

  BaseMongoStorage(this.config);
}
```
