### ISSUE TITLE
I got pub get failed 

### ISSUE THREAD

**Issue by threepat1** [mongo-dart/mongo_dart#226]
because mongo_dart >=0.3.3 <0.5.0-beta depends on bson ^0.3.2 which depends on fixnum ^0.10.8. but I use other package like built_value which depend on fixnum 1.0.0 I try to downgrade but It seems looping to downgrade all but still doesn't work. 

it would be great if you please upgrade fixnum 1.0.0 to solve this conflict

**Comment by giorgiofran** [comment]
At present there are three releases that are at the same development point but with different dependencies:
- 0.5.0+1
- 0.5.1
- 0.7.0-nullsafety.3

Only the last one has the support for fixnum: ^1.0.0

It is not possible to add support for fixnum in the previous (there are some incompatibilities that I have not the time to solve).

**Comment by giorgiofran** [comment]
I close this issue, feel free to open a new one if needed.
