### ISSUE TITLE
error:  default SecurityContext getter

### ISSUE THREAD

**Issue by korykaradg** [mongo-dart/mongo_dart#227]
rror: MongoDB ConnectionException: Could not connect to cluster1.ssvny.mongodb.net:27017
- Unsupported operation: default SecurityContext getter
- 
- My problem, this could not be solved. Please help.

**Comment by giorgiofran** [comment]
Are you trying to use mongo_dart in a web (Angular/Flutter) application?
Which is the Dart and driver version?

**Comment by korykaradg** [comment]
flutter application 

flutter version: Flutter 2.2.0-10.2.pre

dart version:  Dart 2.13.0

**Comment by giorgiofran** [comment]
Which flavor of flutter application?

**Comment by korykaradg** [comment]
how so , ı dont understand

**Comment by giorgiofran** [comment]
With flutter you can make applications for different platforms: Android, iOS, Linux, Windows, MacOs and Web.
You can use mongo_dart in any of those, with the exception of the Web target. In a web application mongo_dart does not work.

**Comment by giorgiofran** [comment]
I close this issue, feel free to re-open it if needed.

**Comment by hauretax** [comment]
hey ! i try to launch it on android and he do me the same .

**Comment by hauretax** [comment]
he tel me MongoDB ConnectionException: but when i try get my collection in node it work. so im not sure what i doing bad or what happening bad
