### ISSUE TITLE
replaceOne

### ISSUE THREAD

**Issue by paapu88** [mongo-dart/mongo_dart#230]
Dear Developers, 
According to README:
```
replaceOne
You can update the whole document with method replaceOne if you have mongoDb ver 3.6 or greater

  var v1 = await coll.findOne({"name": "c"});
  v1["value"] = 31;
  await coll.replaceOne(v1);
```

When I try to use replaceOne with one parameter I get error (already in Intel IJ editor):
`2 positional argument(s) expected, but 1 found.`

My relevant piece of code:
```
    final db = await mongo.Db.create('mongodb+srv://XXXX:YYYY@ZZZZ.l1pxp.mongodb.net/test? retryWrites=true&w=majority');
    await db.open();
    final coll = db.collection('kayttajat');
    var kayttaja = await coll.findOne({'nimi': widget.userName});
    // .....
   vanhatRastit.add(rasti['rastikoodi'])
   kayttaja[kartta]['rastit'] = vanhatRastit;
   //await coll.save(kayttaja);
   await coll.replaceOne(kayttaja);
   await db.close();
``` 

`await coll.save(kayttaja);` seems to be ok, even if it complains about " 'save' is deprecated and shouldn't be used. Since version 4.2. "

terveisin, Markus

**Comment by giorgiofran** [comment]
Thanks for pointing out this error in the docs. You can give a look to a correct example (link in README) to see how it should be.
In general replaceOne requires at least the selector and the document, so you should probably write your statement like this:
```dart
await coll.replaceOne({'_id': kayttaja['_id']}, kayttaja);
```
I'll fix the docs

**Comment by giorgiofran** [comment]
I close this issue, feel free to re-open it if needed.
