### ISSUE TITLE
working in isolate while app in background

### ISSUE THREAD

**Issue by meridorkobi** [mongo-dart/mongo_dart#231]
Is it supposed to work?
I'm writing to MongoDB atlas.
When app in foreground working OK .
In background, its looking like freezing and after moving to front it write all the data that was freezing

**Comment by giorgiofran** [comment]
Mongo_dart does work in isolate.
I'm not an expert of Flutter, so I don't know if in background apps freeze or not. But this does not depends on isolates (I guess).
Try to do something else (like writing into a file) and see if it freeze anyway.

**Comment by meridorkobi** [comment]
I moved the MongoDB insert to listener in initState() and its working on Android  in foreground and background.
On iOS only in foreground. 
I enabled the following in info.plist
What is missing? 


```
	<key>UIBackgroundModes</key>
	<array>
		<string>audio</string>
		<string>bluetooth-central</string>
		<string>external-accessory</string>
		<string>fetch</string>
		<string>location</string>
		<string>remote-notification</string>
	</array>

```

**Comment by meridorkobi** [comment]
Add the uuid to scan command
flutterBlueInstance.scan( withServices: [Guid("XXXuuidXXXX")] ).listen((
