### ISSUE TITLE
having issues using aggregate

### ISSUE THREAD

**Issue by trailerzone** [mongo-dart/mongo_dart#232]
```
Future<Map> commonFriends(store, myObjectId, theirObjectId) async {
  var commonList = await store.aggregate([
    {
      '\$project': {
        'friends': 1,
        'commonToBoth': {
          '\$setIntersection': [
            {
              '_id': myObjectId,
            },
            {
              '_id': theirObjectId,
            }
          ]
        },
      }
    }
  ]);
  return commonList;
}
```

my database structure looks like this

```
{
"_id" : ObjectId("60ae06074e162995281b4666"),
"email" : "one@one.com",
"emailverified" : false,
"username" : "one@one.com",
"displayName" : "complete n00b",
"phonenumber" : "",
"dob" : "",
"points" : 0,
"friends" : [
    {
        "username" : "three@one.com",
        "sent" : ISODate("2021-05-26T10:01:30.616Z")
    },
    {
        "username" : "six@one.com",
        "sent" : ISODate("2021-05-26T10:43:16.822Z")
    }
]
```

but I am getting a response back from the plugin that says: "Exception has occurred.
Map (4 items)" it is coming from db.dart and it is coming from line 491 which is apart of executeDbCommand function

**Comment by giorgiofran** [comment]
I never used `$setIntersection`, so I cannot help you. At a first glance it seems to me that is not to be used like you do.
I suggest you to give a look to the documentation (MongoDb docs example uses string that are by far easier to manage than documents), and try to make it work first in the mongo shell. Than you will be able to port it easily to mongo_dart.

**Comment by giorgiofran** [comment]
I close this issue, feel free to re-open it if needed.
