### ISSUE TITLE
Will the .watch() will work while the app in the background?

### ISSUE THREAD

**Issue by meridorkobi** [mongo-dart/mongo_dart#233]

**Comment by giorgiofran** [comment]
I'm sorry, I never testes this case.
If the isolate is active, it should work, but I don't know if a background task on android is periodically frozen/released.
We have also had a case in which, connecting to Atlas, the connection was closed by the peer after a while. see #228

**Comment by meridorkobi** [comment]
Thanks
Is it better to use trigger from MongoDB atlas to notify the app?
Kobi

**Comment by giorgiofran** [comment]
I never used triggers from MongoDb Atlas, so I cannot suggest how to use them.

**Comment by giorgiofran** [comment]
I'm closing this issue, feel free to re-open if needed

**Comment by WONDERJEWEL** [comment]
Yes it is possible I used it
