### ISSUE TITLE
Not working in flutter web

### ISSUE THREAD

**Issue by Flaming19** [mongo-dart/mongo_dart#235]
Error in flutter web: 
MongoDB ConnectionException: Could not connect to cluster0-shard-00-00.jhnov.mongodb.net:27017
-> Unsupported operation: default SecurityContext getter

Same code is working in flutter Android and IOS but not working in Flutter web.
Could anyone help me in this

**Comment by giorgiofran** [comment]
Unfortunately not. mongo_dart does not work in a "web" environment, as it is clearly stated in the README file. See the pub site.
