### ISSUE TITLE
First of all, I really appriecate the work you guys have done.

### ISSUE THREAD

**Issue by mattjslaton** [mongo-dart/mongo_dart#237]
love the plugin, I clicked through to find out how to use limit on pipeline but not sure where to add it into my code, I am requesting chat history, but I'd like to get it back with 30 at a time. I tried to put ```.addStage(Limit(30)) ``` in the code below but, I think I am putting it in the wrong spot or misunderstanding the documentation inside the plugin, could you help me out real quick and give me some pointers on where it might work within this pipeline query?  

I know you guys are probably all really busy so thanks in advance, I appreciate the project and any pointers in regards to which direction I should go with regards to limiting the query within the pipeline below.

```      final pipeline2 = AggregationPipelineBuilder()
          .addStage(Match(where.eq('_id', theirId).map['\$query']))
          .addStage(
              Match(where.eq('messages.username', myUsername).map['\$query']))
          .addStage(Project({
            '_id': 0, //You can use as:'customer' instead of this keyword.
            'messages': Filter(input: '\$messages', cond: {
              '\$eq': ['\$\$this.username', myUsername]
            }).build(),
          }))
          .build();
```

**Comment by mattjslaton** [comment]
if anyone is interested, what i am attempting to do is pagination on a nested array called messages, so limit cannot be used for this purpose since limit() is meant for top level documents, what is required is slice(), in mongo shell to achieve the outcome it is db.users.find({}, { _id: toplevelId, "messages": { $slice: [0,1] }}).limit(1).pretty() this returns sub documents 0-1 within messages array of the top level objectId database entry for the collection of users. the the idea is to get the count of the sub documents within the array first, store that into a int and from there use that to paginate properly, i know i am annoying but if anyone knows how to add the slice command to the pipeline above i would be extremely grateful

**Comment by giorgiofran** [comment]
I'm sorry, but I cannot figure out what you would like to do.
If you could provide some example data to understand how your documents are structured and the type of output that you expect, this could help.
In general the feeling I get is that you already have the solution. You could use the `find` (better the `modernFind`) method and use the cursor in order to paginate.

**Comment by mattjslaton** [comment]
> I'm sorry, but I cannot figure out what you would like to do.
> If you could provide some example data to understand how your documents are structured and the type of output that you expect, this could help.
> In general the feeling I get is that you already have the solution. You could use the `find` (better the `modernFind`) method and use the cursor in order to paginate.
> For an example on how to use a cursor [see here](https://github.com/mongo-dart/mongo_dart/blob/main/example/manual/crud/cursor.dart)

Thanks for your reply, here is my db entry. the collection is called users,

```{
	"_id" : ObjectId("60d14fda52e329d4dd2febab"),
	"email" : "roger@one.com",
	"emailVerified" : false,
	"emailOptIn" : false,
	"username" : "roger@one.com",
	"displayName" : "complete n00b",
	"profilePhotoUrl" : "",
	"tagId" : "8aa2ff40-d304-11eb-a189-3795162ca86a2fb03800-d411-4651-b535-1ce5fafd6627",
	"unread" : "",
	"phoneNumber" : "",
	"numberVerified" : false,
	"dob" : "",
	"points" : 0,
	"attended" : 0,
	"hosted" : 0,
	"friends" : [
		{
			"username" : "one@one.com",
			"timestamp" : "2021-06-21 19:52:07.731969"
		}
	],
	"comments" : [ ],
	"commentCount" : 0,
	"friendRequestSent" : [ ],
	"messages" : [
		{
			"id" : "62513b00-d305-11eb-a189-3795162ca86a",
			"username" : "roger@one.com",
			"message" : "hey this is roger",
			"timestamp" : "2021-06-21 19:56:04.272573",
			"threadName" : "62513b01-d305-11eb-a189-3795162ca86a"
		},
		{
			"id" : "74f8ed20-d305-11eb-a189-3795162ca86a",
			"username" : "one@one.com",
			"message" : "hi roger",
			"timestamp" : "2021-06-21 19:56:35.570525",
			"threadName" : "62513b01-d305-11eb-a189-3795162ca86a"
		},``` so I am just keeping track of users and their messages by using a message array that has the username, message timestamp etc, and I am making a request to view messages only sent by a particular user, each user has their own profile document and under their profile document there is a messages array or folder, each message has a username attached to it, so when I use the pipeline to query a user, i filter out all the other messages within the query using the code mentioned above. everything is working fine, I am able to get back the subdocuments or array specifically relating to a certain user. but, I am having a hard time figuring out how to add the slice() function to the pipeline code, I am not sure where to add it. On subdocuments, you cannot use just limit() to limit the results, because limit() is typically used for the parent document, so when making a query, you have to use slice() in mongo shell followed by limit(), not sure why exactly it works but it does do exactly what I am trying to do which is return a limited amount of subdocuments or array entries relating to the user specified, basically I am making a message inbox from the messages array and only showing 1 user at a time as if you opened up a chat window with only one user, you would only get back messages relating to you and him/her. that is what I am trying to do but also limit it so I don't waste resources

**Comment by giorgiofran** [comment]
Sorry, but it is still not clear.
you could have:
```dart
{"_id" : ObjectId("60d14fda52e329d4dd2febab"),
	"email" : "roger@one.com",
	...
	"messages" : [
		{
			"id" : "62513b00-d305-11eb-a189-3795162ca86a",
			"username" : "roger@one.com",
			"message" : "hey this is roger",
			"timestamp" : "2021-06-21 19:56:04.272573",
			"threadName" : "62513b01-d305-11eb-a189-3795162ca86a"
		},
		{
			"id" : "74f8ed20-d305-11eb-a189-3795162ca86a",
			"username" : "one@one.com",
			"message" : "hi roger",
			"timestamp" : "2021-06-21 19:56:35.570525",
			"threadName" : "62513b01-d305-11eb-a189-3795162ca86a"
		},
               {
			"id" : "62513b00-d305-11eb-a189-3795162c1234",
			"username" : "roger@one.com",
			"message" : "hi one",
			"timestamp" : "2021-06-21 19:56:54.272573",
			"threadName" : "62513b01-d305-11eb-a189-3795162ca86a"
		},
               {
			"id" : "62513b00-d305-11eb-a189-379516286547",
			"username" : "roger@one.com",
			"message" : "hey this is roger again",
			"timestamp" : "2021-06-21 20:56:04.272573",
			"threadName" : "62513b01-d305-11eb-a189-3795162ca86f"
		},
		{
			"id" : "74f8ed20-d305-11eb-a189-3795162c4867",
			"username" : "one@one.com",
			"message" : "hi again roger",
			"timestamp" : "2021-06-21 20:56:35.570525",
			"threadName" : "62513b01-d305-11eb-a189-3795162ca86f"
		},
}
```
In this case in the user "one@one.com" what will you store? For a certain user do you want to extract only the messages he wrote existing in his profile?
In the case above you would like to extract three messages?

**Comment by giorgiofran** [comment]
Well, let's say that what you want is to show a window chat for the user "roger@one.com" with the following content:
```
"hey this is roger"
   "hi roger"
"hi one"
"hey this is roger again"
   "hi again roger"
```
In this case we have only five messages, but, as you could have a lot of messages, you would like to extract only 30 (or a certain number) at a time.
Is this the case?

If it is this, I believe that what you would like to do it is not possible. I'm not aware of a an operator in the aggregation pipeline that allow you to project the data it contains and in a second call project it in a different way.
But, in general, I would suggest you a different approach.
I assume that the messages array can grow in the time, as it contains all the messages of the user.
Consider also that a single document has a limit of space, so, if the number of messages is very high, you could potentially reach that limit.
I suggest you to create a separated collection, called "messages", where you will have the user key as reference
```
{
                       "userId" : ObjectId("60d14fda52e329d4dd2febab")
			"id" : "62513b00-d305-11eb-a189-3795162ca86a",
			"username" : "roger@one.com",
			"message" : "hey this is roger",
			"timestamp" : "2021-06-21 19:56:04.272573",
			"threadName" : "62513b01-d305-11eb-a189-3795162ca86a"
		},
```
At this point you could use a simple find and paginate with the cursor.

**Comment by mattjslaton** [comment]
okay cool, thank you. i was kind of assuming that if that was not possible that i would build a separate collection, so that is very helpful. it actually probably has better performance as well considering there won't be any extra combing through entries looking for subdocumens that pertain to a certain user. thanks for the clarification, that is very helpful

**Comment by giorgiofran** [comment]
I close the issue, feel free to reopen it if needed
