### ISSUE TITLE
Thanks a lot for this package, when do you people think that it will work for the web ?

### ISSUE THREAD

**Issue by Fiziktim** [mongo-dart/mongo_dart#239]
I have just spent a few hours on this : 

Tried to make dart_mongo work with flutter, it didn't. 
I had the same obscure java or javascript errors, pointing to a hidden file in flutter about cryptography. I even tried to change the file slightly as the error suggested me to do. But it didn't work, so I put it back to normal.

My code worked very well in dart, but not in flutter. And I realised that the problem came form importing mongo_dart. 

Again, thanks so much for this package !

I searched for a solution for a long time. But then, looking at the mongo_dart page, I realised that it was available for everything but web.

And it made sense, I was running my app on Chrome.

It seems really strange to me that it is not the default for such a package to be completely platform agnostic... I mean... It doesn't render anything does it.. 

But I guess that what is happening, (as you can see, I am rather a beginner with flutter) is that flutter has to compile its code into web readable code, with I guess, a lot of javascript. Feature that mongo_dart does not support yet, while it does work in swift or java. For both iOs and Android platforms. That would explain that the obscure error would point to a Java value that was unreadable with Javascript.

All of that, really, to ask the question in the title...

Thank you again, this package is kind of a life saver !

It would be a blessing to have this working for web as well, I do not realise how little or how much work that would be though.

Have a good day

**Comment by giorgiofran** [comment]
I really don't know. The problem is due to dart:html missing support of sockets. I have seen a package that may solve the problem, but I should test it. It is not something to be solved soon.

**Comment by Fiziktim** [comment]
Alright, thanks a lot for your answer 🙏 Good luck

**Comment by Fiziktim** [comment]
Alright, thank you 🙏 and good luck !

**Comment by tamereratik** [comment]
i know  dart:html supports of sockets. exactly  where is the problem? what do you think?

**Comment by giorgiofran** [comment]
I'm not aware of any socket implementation in `dart:html`, could you please give me a reference to this documentation?

**Comment by tamereratik** [comment]
i do not know what you need about sockets and where the sockets needs in mongo_dart. But here there is a web-socket class. 
https://api.dart.dev/stable/2.13.4/dart-html/WebSocket-class.html

**Comment by giorgiofran** [comment]
Sockets and WebSockets are two different things. Googling a little I found this explication:

```
A socket is one endpoint of a two-way communication link between two programs running on the network. 
This is a very low-level thing, everything else is implemented on top of TCP sockets.
 
WebSocket is a standard communication protocol for the web. 
It allows for a full-duplex communication channel to be established between a client and a server.
```

**Comment by giorgiofran** [comment]
I have check, and unfortunately iy is not possible to use mongo_dart in the web environments. I will open a point in the discussion to talk about what can be done
