### ISSUE TITLE
Encryption data

### ISSUE THREAD

**Issue by meridorkobi** [mongo-dart/mongo_dart#242]
Do we have option to encrypt the data?
To make it difficult for unauthorized people to see the data

**Comment by giorgiofran** [comment]
When we talk about encrypting data we  can divide the problem at least in three parts:

- encryption at rest
- transport encryption
- client side encryption

Encryption at rest means that data is encrypted on disk. If someone tries to read a back-up of your, he will not be able to read any data. It is available only on the [enterprise MongoDb version](https://docs.mongodb.com/manual/core/security-encryption-at-rest/).
If you cannot afford an enterprise version (like me ;-) ), you can do something tricky that works, unless you have not an high volume of data (at that point it is probably worth to move to enterprise edition ...).
On Linux, create a file system in an encrypted file (I used veracrypt) and move you MongoDb data inside it.
This approach as the counter-effect that, any time you have to restart the server, you have to open the encrypted file system and restart mongod. But it protects you if someone give a look to your backups. It does not protect you if someone access your system while it is running though.

Transport encryption can be set using TLS. You can give a look into mongo_dart doc/manual/connection folder to get some hints.

Client side encryption is not yet managed from mongo_dart. Is a nice to have feature, but I have not the time now to develop it.
You can give a look at the MongoDb documentation [here](https://docs.mongodb.com/manual/core/security-client-side-encryption/)

**Comment by meridorkobi** [comment]
Thanks Giorgio,
I'm working with MongoDB atlas and I can not use local encryption.
I will check the enterprise options. Do you know other option relevant to
Atlas?
I m useing the transport encryption by open with security.
At this time I don't need to encrypt the client side

Thanks
Kobi

**Comment by giorgiofran** [comment]
I do you use Atlas mainly for testing. I'm not an expert.

**Comment by giorgiofran** [comment]
I close this issue, feel free to re-open it if needed.
