### ISSUE TITLE
Support for MongoDB 5.0

### ISSUE THREAD

**Issue by gfyre** [mongo-dart/mongo_dart#243]
Hey guys, for starters, thanks a ton for building this package.

What I'd like to know is if this package has support for Mongo 5.0

If not then what version is it most stable on? Can I use this in production?

Thank you!

**Comment by giorgiofran** [comment]
I run tests on 5.0 right now and everything seems to be OK.
Obviously no changes have been made yet to support new features.
I do use this package in production

**Comment by giorgiofran** [comment]
I'm closing this issue, feel free to re-open if needed
