### ISSUE TITLE
Syncing clients to Mongo server time

### ISSUE THREAD

**Issue by natgross** [mongo-dart/mongo_dart#244]
What is the quickest way of getting server time *without* writing? The purpose is to get all clients to exactly the same time +- a few milliseconds (on the same lan). Syncing my Android devices to ntp server can be off by a few seconds (I don't know why). So I want to use the mongo server as a time server. 
Scenario as follows.  
1. A device inserts a document using objectId or other server-side date/iso date.
2. All clients read that document, including the aforementioned time in it.
3. All clients display (educational type of app) seconds elapsed since document was inserted, and/or x seconds remaining until a minute has elapsed.
In order to do this, I have to know the time difference between the client and the server. So I am looking for a server call to just tell me the time now, no writing involved, that would be called every hundred milliseconds or so.
Thanks. -nat

**Comment by giorgiofran** [comment]
Maybe you can use the isMaster command
```
isMaster.localTime
    Returns the local server time in UTC. This value is an ISO date.
```

Beware that `isMaster` command has been deprecated in mongodb in favor of the `hello` one.
Unfortunately the `hello` command is not yet available in mongo_dart. I'm working on it and it should be present in the next version.

**Comment by natgross** [comment]
[After testing...] Looks ok to me! 
Thanks.
