### ISSUE TITLE
Certificate not working

### ISSUE THREAD

**Issue by enyo** [mongo-dart/mongo_dart#246]
Hi,

I'm trying to get this library to work with digital ocean mongodb. When you setup a database there, you get a CA certificate:

<img width="286" alt="image" src="https://user-images.githubusercontent.com/133277/132121324-90064d6d-b2d0-4c9b-88a3-8f5cb29b0b31.png">

They also provide a connection string to be used, which looks like this:

```sh
mongo "mongodb+srv://local-dev:password@db-mongodb-fra1-xxxyyy-xxyyy.mongo.ondigitalocean.com/database?authSource=admin&replicaSet=db-mongodb-fra1-foo" --tls --tlsCAFile <replace-with-path-to-CA-cert>
```

So I took this, replaced, the `<replace-with-path-to-CA-cert>` with the path to the downloaded certificate and it worked fine! I could connect to the server.

I then tried doing the same with `mongo_dart` by

1. adding the path in the URL, and
2. providing the path to the `db.open(tlsCAFile: '/my/path)` function, but I get this:

```
[SEVERE] ConnectionManager: MongoDB ConnectionException: Could not connect todb-mongodb-fra1-xxxyyy-xxyyy.mongo.ondigitalocean.com:27017
- HandshakeException: Handshake error in client (OS Error: 
        CERTIFICATE_VERIFY_FAILED: application verification failure(handshake.cc:359))
Unhandled exception:
MongoDB ConnectionException: Could not connect to db-mongodb-fra1-xxxyyy-xxyyy.mongo.ondigitalocean.com:27017
- HandshakeException: Handshake error in client (OS Error: 
        CERTIFICATE_VERIFY_FAILED: application verification failure(handshake.cc:359))
#0      _ConnectionManager.open (package:mongo_dart/src/network/connection_manager.dart:94:9)
```

This is what my dart code looks like:

```dart

  final connectionstring =
      'mongodb+srv://local-dev:password@db-mongodb-fra1-xxxyyy-xxyyy.mongo.ondigitalocean.com/database?authSource=admin&replicaSet=db-mongodb-fra1-foo';
  final db = await Db.create(connectionstring);
  await db.open(
      secure: true,
      // tlsAllowInvalidCertificates: true,
      tlsCAFile: '/path/to/ca-certificate.crt');
```

Any help would be much appreciated!

(P.S.: I obfuscated my connection strings)

**EDIT**: If I add `tlsAllowInvalidCertificates: true` to the `.open()` method, then it works, so the connection string is correct.

**EDIT 2**: I did some more testing and added a few breakpoints, and I can see that the `ServerConfig.tlsCAFileContent` does contain the content of my downloaded crt file

**Comment by enyo** [comment]
I'm more and more confused by this. So I dug a bit deeper, and found these lines in `src/network/connection.dart`:

```dart
        _socket = await SecureSocket.connect(
            serverConfig.host, serverConfig.port, context: securityContext,
            onBadCertificate: (certificate) {
          // couldn't find here if the cause is an hostname mismatch
          return serverConfig.tlsAllowInvalidCertificates;
        });
```

So I did some debug output here, and inside the `onBadCertificate` the `certificate.pem` is exactly the certificate that is stored in `serverConfig.tlsCAFileContent`... I don't understand how that's possible.

**Comment by giorgiofran** [comment]
Is difficult to say. Working with certificates is not that easy!
What I can say is that, when I did my tests, I noticed that the CaFile must contain the full chain of certificates.
That means that if the file that you have downloaded contains only the last certificate level, you should concatenate also the higher levels.
I guess that this is a specific behavior of the Dart socket layer (i.e. Google, it should be the same in Chrome also).
It seems to me that the difference with other implementations (like the mongo shell) is that Dart's one verifies all the certificate chain, while the others only the last level.
If what I'm saying is true, you should search in the Digital Ocean site for the full chain CaCertificates and try to use them.
Remind also that, in my experience, it is also important the order in which the file contains the certificates. 
They should be concatenated starting with the lower levels up to the higher ones.
I found no documentation about this, I discovered this by "trial and error" efforts.

**Comment by enyo** [comment]
I'll try and report back

**Comment by enyo** [comment]
Unfortunately I didn't get it to work. Thank you so much for your help though!

I went to digitalocean.com and opened the certificate in firefox:

There are three listed:
<img width="865" alt="image" src="https://user-images.githubusercontent.com/133277/132125386-340a421a-0f31-4b24-97b9-806600f80a18.png">

I assume it's not the first one, because 1) it expires soon, and 2) it's purpose is "Digital Signature" and not "Digital Signature, Certificate Signing, CRL Signing" like the other two.

So I exported the other two certificates as chains as well, and tried putting them after (but also before) my certificate, and none worked... Do you have any suggestion on how I could proceed here?

**Comment by giorgiofran** [comment]
The first certificate expires in May 2022, It is not so soon. Normally the duration is even shorter (6 months or so on). I'd try to use it.
Create a full_chain.crt with (in order): <your-server-crt>, <digital-ocean-crt>, <cloudfare-inc-crt> and <baltimore-cyber-trust-root> and then try again.

**Comment by enyo** [comment]
@giorgiofran I also tried this, but to no avail.

I realised now, that this problem only happens on my local macOS machine. When I tried the same on a linux machine it worked fine... 🤷 

Oh well, a day wasted for nothing I guess.

Thank you so much for your help again Giorgio! It wasn't really related to your library in the end but your help is really much appreciated. Have a great day.

**Comment by giorgiofran** [comment]
Which `.crt` chain worked fine (just curious)?

**Comment by enyo** [comment]
@giorgiofran the original `.crt` without any chain.
