### ISSUE TITLE
How to verify connection is ok

### ISSUE THREAD

**Issue by meridorkobi** [mongo-dart/mongo_dart#248]
I would like to verify that the connection to MongoDB is OK at initstate().
Display a wait page until connection is OK and then change to the real page.
For example going down to paging area without network and then up.
What is the best way to get the MongoDB connection status?

**Comment by giorgiofran** [comment]
Probably `db.isConnected` is a good choice

**Comment by giorgiofran** [comment]
I close this issue, feel free to re-open it if needed.
