### ISSUE TITLE
Get collection

### ISSUE THREAD

**Issue by meridorkobi** [mongo-dart/mongo_dart#249]
My App uses 5 collections, 2 of them intensively. What is better to do:
1. To get and save the all the collection pointers in static variables at the beginning. 
2. To get the collection pointer each time before using the collection. 

Thanks

**Comment by giorgiofran** [comment]
The call to `collection` simply creates a `DbCollection` object.
I guess is more efficient to create them and store to be reused, as continuously creating object is not very efficient.
This said, you have to remind to delete your saved `collection` instances in case of `db.close`.

**Comment by meridorkobi** [comment]
Thanks I will do it
