### ISSUE TITLE
Cannot translate the aggregation into the expected format.

### ISSUE THREAD

**Issue by KurtLa** [mongo-dart/mongo_dart#250]
Hi folks,
I need to translate the following pipeline into the desired format.

```
[{$group: {
  _id: "$isin"
}}, {$lookup: {
          from:"itemvalues", 
          as:"items", 
          let:{g:"$_id"},
          pipeline:[ 
               {$match:{$expr:{$eq:["$itemID","$$g"]}}}, 
                {$sort:{t:-1}},
                {$limit:20}, 
               {$project:{_id:0, ItemID:1, a:1, b:1, t:1}}
          ]
     }}]
```

i dont see any way to inject the Let(...) and the sub-pipeline into
` Lookup(from: from, localField: localField, foreignField: foreignField, as: as)
`

Do i miss anything? Is there a way to pass my aggregation as a simple escaped string or something?

Cheers,
Kurt

**Comment by giorgiofran** [comment]
Try with `Lookup.withPipeline()`, or use `modernAggregate`. The  latter allows you to pass the pipeline as a map without the need of the `AggregationPipelineBuilder()`.

**Comment by KurtLa** [comment]
Ah, great. Thank you very much. I will try that.
