### ISSUE TITLE
Connecting string to MongoDB Atlas

### ISSUE THREAD

**Issue by meridorkobi** [mongo-dart/mongo_dart#251]
What is the best and fast string to connect to M2 for read & write + ssl?
Now its about 4 sec.

My current string -
"mongodb://User:Pass@cluster0.ZZZZ.mongodb.net,cluster0-shard-00-00.ZZZZ.mongodb.net:27017,cluster0-shard-00-01.XXXX.mongodb.net:27017,cluster0-shard-00-02.ZZZZ.mongodb.net:27017/WJ?ssl=true&replicaSet=atlas-razveo-shard-0&authSource=admin&retryWrites=true&w=majority"

**Comment by meridorkobi** [comment]
Thanks
At this time working with MongoDB Atlas.
The connection is the first process in my app. and I would like to decrease it.
Can I do something in Atlas definitions ? or any idea?
Thanks 
Kobi

**Comment by giorgiofran** [comment]
I close this issue, feel free to re-open it if needed.
