### ISSUE TITLE
Can only connect to admin db

### ISSUE THREAD

**Issue by jinyus** [mongo-dart/mongo_dart#255]
I am unable to connect to other Databases. The code below works fine
```var db = Db('$mongoURI/admin');```

but when I change admin to another database on the server, I get an auth error:
```var db = Db('$mongoURI/users');```
gives:
```
Unhandled exception:
MongoDart Error: Authentication failed.
#0      _ConnectionManager.open (package:mongo_dart/src/network/connection_manager.dart:145:9)
<asynchronous suspension>
#1      Db.open (package:mongo_dart/src/database/db.dart:456:7)
<asynchronous suspension>
```

I can list the databases when I connect with the admin db but I cannot select one.

I tried [this answer](https://stackoverflow.com/a/14634442) on stackoverflow but it didn't work.

edit:
it's working with python and golang so there might be a problem with how you're handling authentication. I'm using a fresh docker install so my issue should be easy to replicate.

```
sudo docker run --name mongo1 -p 27017:27017 -e MONGO_INITDB_ROOT_USERNAME=YOUR_USERNAME -e MONGO_INITDB_ROOT_PASSWORD=YOUR_PASSWORD -d mongo:5.0.3
```
Dart code that didn't work:
```
final mongoURI = Platform.environment['MONGO_LOCAL_URI']!;
final db = Db('$mongoURI/databasename');
await db.open();
```

Python code that worked:
```
from pymongo import MongoClient
import os 

mongo_uri = os.environ['MONGO_LOCAL_URI']
client = MongoClient(mongo_uri)

resp = client.databasename.command('ping')
if resp['ok'] != 1.0:
    exit('connection failed')
else:
    print('connection success')
```

**Comment by giorgiofran** [comment]
Your Uri does contain user and pasword?

**Comment by jinyus** [comment]
Thanks, adding authSource worked. 
You might want to automatically use admin as the auth source if one isn't provided. That's how it's done in the [pymongo package](https://github.com/mongodb/mongo-python-driver/blob/2af521ec03eab88ad5c9ebef0f73025c00489604/pymongo/mongo_client.py#L406).

**Comment by Kings-Samuel** [comment]
Hey @giorgiofran , the authSource=admin param does not work for me

**Comment by giorgiofran** [comment]
Which is the error?

**Comment by giorgiofran** [comment]
Could you solve the issue?

**Comment by coolcreation** [comment]
Thanks to @giorgiofran 

This solution worked great ( just for practice, not production):
URI=mongodb://127.0.0.1:27017/myDatabase?authSource=admin
