### ISSUE TITLE
Realm cluster and authentication

### ISSUE THREAD

**Issue by nysoftwarelab** [mongo-dart/mongo_dart#256]
I m trying to authenticate an app user using a realm cluster.
In the server I have a few "app users" with username/password auth setup.
I always get "Authentication failed" error.

Have you ever tested with realm tier ?
Do you have an example ?

**Comment by nysoftwarelab** [comment]
No I didn't, plus realm_dart its not null safety compatible ... to much trouble even for a test.

**Comment by nysoftwarelab** [comment]
Checked the authentication process. 
In the db.dart file you have the `authenticate()` function with `UsernamePasswordCredential` which is fine but we need to set the authProvider to to something else like `local-userpass`.
see : `https://docs.mongodb.com/realm/authentication/providers/`

It would be awesome if we can have this in the future as an option.

If you need any tests and help with realm let me know.
Hope that helps.

**Comment by giorgiofran** [comment]
As far as I know, realm and MongoDb are two different databases. Are you sure that, after connecting, everything will work fine? 
It seems that the realm_dart repository is actively maintained. Giving a look to the pubspec.yaml in the master branch, I saw that it is a null-safety version, so maybe that something will roll out soon. Better, you could ask for a roadmap. 
[See this](https://github.com/realm/realm-dart/issues/32)

**Comment by nysoftwarelab** [comment]
100% sure.
After I connect with connection string that contains Username/Password everything works fine, all CRUD operations tested.
The only problem is that Username/Password comes from `Atlas Database Access` section and not from `App Users` in Realm.

Besides that my app work perfect tho.

About the realm_dart repository I saw that they describe the repo as : `Realm is a mobile database that runs directly inside phones'
That's not what I want

**Comment by giorgiofran** [comment]
> The only problem is that Username/Password comes from Atlas Database Access section and not from App Users in Realm tier

I'm sorry, but I didn't get exactly how it works.
Can't you provide a PR?

**Comment by nysoftwarelab** [comment]
```
var connectionString ="mongodb://[username:password@]host1:27017,host2:27017/testdb?ssl=true&replicaSet=atlas-xxx-shard-0&authSource=admin&retryWrites=true&w=majority";

Db db = Db(connectionString);
await db.open();
```

OR 

```
var connectionString ="mongodb://host1:27017,host2:27017/testdb?ssl=true&replicaSet=atlas-xxx-shard-0&authSource=admin&retryWrites=true&w=majority";

Db db = Db(connectionString);
await db.open();

db.selectAuthenticationMechanism("SCRAM-SHA-1");
await db.authenticate('[username]', '[password]');

```

Both work but with Atlas Database Access users ... I want to use the App Users in Realm tier ... see pics
![Screenshot_1](https://user-images.githubusercontent.com/58887723/144620997-5fe11240-ba79-4800-8e23-4935348610df.jpg)
![Screenshot_2](https://user-images.githubusercontent.com/58887723/144621020-6b74ec56-8d59-4aac-b0b1-dfc487e39b56.jpg)

**Comment by giorgiofran** [comment]
I'm sorry I do not know how to connect to a Realm tier, if you want me to help you, I need technical details.
Up to now you told me that you are able to connect to Atlas, that it is backed by mongoDb. And that is OK.
But, How could I connect to a realm tier? Should you need a different connection string (something like "realm://")?

**Comment by dudizimber** [comment]
I believe the question is if it is possible to create the connection with the connection string mentioned in [this link](https://docs.mongodb.com/realm/mongodb/connection-strings/).

When I try it, I get the following error:
![image](https://user-images.githubusercontent.com/16744955/150106038-7cad0dfe-2167-4528-9d05-9b238f6cb98f.png)

**Comment by giorgiofran** [comment]
The app name is something of the realm backend. In MongoDb server there is not such a concept.
This is not a driver for realm...

**Comment by giorgiofran** [comment]
I'm closing this issue, feel free to re-open if needed
