### ISSUE TITLE
Watch changes in a collection (insert + update + delete) with filter 

### ISSUE THREAD

**Issue by nysoftwarelab** [mongo-dart/mongo_dart#257]
I want to watch changes in a collection with a filter as a second stage.

If I watch one operation type everything works fine, but that doesn't work if I choose to watch 2 or more operation types "Update" OR "Insert" 

<pre>
getTeamNotesChangesTest(String teamId) {
    var collection = db.collection('notes');
    dynamic oId = ObjectId.parse(teamId);
    var pipeline = AggregationPipelineBuilder()
        .addStage(
          //Match(where.match('operationType', 'insert').map['\$query']), //<-This works fine
          Match(where.eq('operationType', 'update').map['\$query']), //<-This works fine
          //Match(where.eq('operationType', 'delete').map['\$query']), //<-This works fine
          //Match(where.eq('operationType', 'update').or(where.eq('operationType', 'insert')).map['\$query']), //<-doesn't works
        )
        .addStage(
          Match(
            where.eq('fullDocument.team', oId).map['\$query'],
          ),
        );
    Stream stream = collection.watch(pipeline);
    return stream;
  }
</pre>

BUT ... this works fine but I cannot add a filter !!!
Any ideas ?

<pre>
Stream stream = collection.watch(<Map<String, Object>>[
      {
        r'$match': {
          'operationType': {
            r'$in': ['insert', 'update', 'delete']
          }
        },
      }
    ]);
</pre>

**Comment by giorgiofran** [comment]
What do you means with "it doesn't work"?
I did some testing and everything seems to work fine.
I could use the `or` statement in the pipeline, and I could add a stage in the explicit map.

Maybe you forgot the `changeStreamOptions` (without these only updated field are returned).
 `var stream = collection.watch(pipeline , changeStreamOptions: ChangeStreamOptions(fullDocument: 'updateLookup'));`

**Comment by nysoftwarelab** [comment]
Maybe its the `ChangeStreamOptions` I have to test it again.
I was thinking that since I set a stage with `Update, Insert, Delete` options I shouldn't define again the ChangeStreamOptions.
Thanks

**Comment by giorgiofran** [comment]
I close this issue, feel free to re-open it if needed.
