### ISSUE TITLE
Connection to database fails with 'No Primary'

### ISSUE THREAD

**Issue by JensHor** [mongo-dart/mongo_dart#258]
I have a mongo db replica set hosted on kubernetes. 

My connection string looks like this:
`mongodb://<user>:<password>@0.0.0.0:8000/?authSource=admin&authMechanism=SCRAM-SHA-256&readPreference=primary&ssl=false` and i am forwarding the service to `localhost:8000` via `kubectl`. 

**The Problem**
The command `await mongoDb.open();` fails with the following message 

> MongoDart Error: No Primary found

I debugged into `mongo_dart` and figured out that a runCommand `db.runCommand( { hello: 1 } )` is executed, which fails with 

> no such command: 'hello'

therefore the library thinks that there is no `_masterConnection` which leads to the error message 'No Primary found'.

I tried the same command in MongoDB Compass and it fails with the same error. However, running `db.hello()` does work.

**Version:**
I am using MongoDB 4.7.2 Community

Am i doing something wrong or is this a bug?

**Comment by giorgiofran** [comment]
I guess that the problem is that there i no explicit database name in the connection string (`mongodb://<user>:<password>@0.0.0.0:8000/test?authSource=admin&authMechanism=SCRAM-SHA-256&readPreference=primary&ssl=false`)
Please let me know if this is the case.

**Comment by JensHor** [comment]
That's indeed the problem 😅. Thanks for helping me out 👍🏻
