### ISSUE TITLE
How to add Object to Array 

### ISSUE THREAD

**Issue by meridorkobi** [mongo-dart/mongo_dart#261]
How to do the following example in dart

Add another animal into the animalArray
db.animal.update(
      { "_id": "100" },
      {
          $push: {
              animalArray: "cat"
          }
      }
  );

**Comment by giorgiofran** [comment]
var res = await db.animal.modernFindAndModify(
      query: where.eq('_id', '100'),
      update: ModifierBuilder().push('animalArray',  'cat'));

**Comment by meridorkobi** [comment]
Thanks
