### ISSUE TITLE
Timestamps

### ISSUE THREAD

**Issue by tomassasovsky** [mongo-dart/mongo_dart#263]
How can i set up timestamps?

**Comment by giorgiofran** [comment]
What do you mean exactly?

**Comment by tomassasovsky** [comment]
https://mongoosejs.com/docs/guide.html#timestamps just like this

**Comment by giorgiofran** [comment]
At present you cannot manage the schema from the driver.
To create a Timestamp Object You have give the number of seconds sinch epoch (TimeStamp(25000)) and then insert into the map that you send to the server.
Give a look to [\example\manual\crud\find_one_by_date.dart](https://github.com/mongo-dart/mongo_dart/blob/main/example/manual/crud/find_one_by_date.dart)

**Comment by giorgiofran** [comment]
I'm closing this issue, feel free to re-open if needed
