### ISSUE TITLE
delete many where all ids not working

### ISSUE THREAD

**Issue by a-eniou-pvotal** [mongo-dart/mongo_dart#264]
I have a list of ObjectId and I tried to delete all of it but it is not working
```
await companyCollection?.deleteMany(
      where.all('id', ids),
    );
```

**Comment by giorgiofran** [comment]
At  a first glance  I would suggest you to use `'_id'` instead of `'id'`

**Comment by a-eniou-pvotal** [comment]
await companyCollection?.deleteMany(
      where.all('_id', ids),
    );

**Comment by giorgiofran** [comment]
If you use `where.all` the documents to be selected are those that match all the values you give, [see the mongoDb docs](https://docs.mongodb.com/v4.2/reference/operator/query/all/).
If you want to select records if at least one of the values you give is matched you have to use `where.oneFrom`, or a map like
```
{
  '_id': {
    r'$in': ids
  }
}
```

**Comment by a-eniou-pvotal** [comment]
Thanks, I got it
