### ISSUE TITLE
Detect changes in connection

### ISSUE THREAD

**Issue by JensHor** [mongo-dart/mongo_dart#265]
I've got the [MongoDB Community Kubernetes Operator](https://github.com/mongodb/mongodb-kubernetes-operator) hosted via Google Kubernetes Engine (GKE) and connecting to with it via `mongo_dart` which works fine. This is my connection string:

```dart
Db(
  'mongodb://$_userName:$_password@'
  '$_replicaSet-0.$_service.$_namespace.svc.cluster.local:$_port,'
  '$_replicaSet-1.$_service.$_namespace.svc.cluster.local:$_port,'
  '$_replicaSet-2.$_service.$_namespace.svc.cluster.local:$_port/'
  '$_database?'
  'authSource=admin&authMechanism=SCRAM-SHA-256&'
  'readPreference=primary&'
  'ssl=false',
)
```

However, sometimes the replica sets on GKE restarts causing the connection to become invalid which will render my service non-functional. 

Is there an option to detect changes in the connection so i can reconnect to the restarted replica set? Or can I adjust the connection string so the restarting replica set does not effect my application? 

I will also post an issue/question on the [MongoDB Community Kubernetes Operator](https://github.com/mongodb/mongodb-kubernetes-operator) since i'm not sure how to tackle the problem (yet).

**Comment by giorgiofran** [comment]
Unfortunately there is no easy way to do that.
To know if you are connected you can check `db.isConnected`..
The only way, at present is periodically checking if you are connected and, otherwise reconnect.

**Comment by JensHor** [comment]
Alright. Is calling `db.isConnected` computationally expensive or is it fine if i check it every 15 seconds?

**Comment by giorgiofran** [comment]
It is fine.
