### ISSUE TITLE
MongoDart Error: No master connection

### ISSUE THREAD

**Issue by graphicbeacon** [mongo-dart/mongo_dart#269]
Hello, I firstly want to thank you for this solution and your hard work so far :) 

I have the following error that appears when invoking the `findOne()` method in an AOT compiled Dart binary running in a Docker container.

```
MongoDart Error: No master connection
package:mongo_dart/src/network/connection_manager.dart 19:7 _ConnectionManager.masterConnectionVerified
package:mongo_dart/src/database/db.dart 198:32 Db._masterConnectionVerifiedAnyState
package:mongo_dart/src/database/db.dart 191:12 Db._masterConnectionVerified
package:mongo_dart/src/database/dbcollection.dart 134:12 DbCollection.findOne
package:spa_server/src/auth_api.dart 69:32 AuthApi.router.<fn>
```

This is happening with **mongo_dart: ^0.7.4**

Here's my Dockerfile:

```Dockerfile
FROM dart:stable
RUN apt -y update && apt -y upgrade

WORKDIR /app
COPY pubspec.* .
RUN dart pub get
COPY . .
RUN dart pub get --offline
RUN dart compile exe bin/server.dart -o bin/server

FROM alpine
COPY --from=0 /app/bin/server /app/bin/server
# COPY any other directories or files you may require at runtime, ex:
COPY --from=0 /app/public/ /app/public/
EXPOSE 12021
CMD ["/app/bin/server"]
```

Should mention that this **does not happen when running in JIT mode**. Is there anything I need to be aware of with outgoing connections from a compiled binary?

**Comment by giorgiofran** [comment]
Unfortunately it seems that the connection has been lost.
To reconnect safely you should close the db 
`await db.close();`
and reopen it
`await db.open();`
You could prevent the error testing the `db.isConnected` getter before calling the `findOne()` method.

**Comment by graphicbeacon** [comment]
@giorgiofran you genius! Thanks so much. It worked. Closing
