### ISSUE TITLE
What is the fastest modernFind?

### ISSUE THREAD

**Issue by WONDERJEWEL** [mongo-dart/mongo_dart#271]
I have a collection with 800 docs. 

I need to find all the Docs with X ="".
Its about 1% of the all Docs. and the other content is fix text like "text" 
I have to user more fields filters but X is the main.
What is the fastest way?
Using view?
index? with all filter fields or only X 
change the field to Boolean (True ="" / False ="text"

**Comment by giorgiofran** [comment]
It is difficult to say. I do normally use indexes. You can also create indexes with a selection, so that they will consider only all docs with X="". 
Probably on the MongoDB site you will find better query optimization technics.

**Comment by WONDERJEWEL** [comment]
Thanks 
I read about this option and tried to set it up (I'm not sure it worked)
But how can I know which index is being used for the a specific modernFind?

**Comment by giorgiofran** [comment]
It is not easy with the driver.
Run your query in mongosh an use [.explain()](https://docs.mongodb.com/manual/reference/method/cursor.explain/)

**Comment by meridorkobi** [comment]
I added some Partial Indexes. Only part of them working.
I know USAGE in indexes tab.
Do I have option to define to use indexes? 
For example
I define index with 2 fields and Partial index on X.
The Explain Plan shows that other index with more fields without Partial used
Can I define priority to use to some indexes?

**Comment by meridorkobi** [comment]
Sorry my bug , the index name was not correct
indEmailDatsSubP >=  indEmailDateSubP

**Comment by meridorkobi** [comment]
Thanks
Its working very nice

**Comment by giorgiofran** [comment]
I close this issue
