### ISSUE TITLE
isConnected for *any* Connection

### ISSUE THREAD

**Issue by natgross** [mongo-dart/mongo_dart#272]
Many times my master connection server (service on Windows 10) simply stops, but the secondary Linux servers are humming along. Technically the db is available ok, but isConnected returns false because the master is down, causing the app to 'think' that the db is not available.
Is there a way to check if db is ok to use? tnx.

**Comment by giorgiofran** [comment]
Unfortunatley the actual driver has a couple of annoying limitations.
The first one is that it always communicate with the primary only, even if you ask for a quety on a secondary. This way, checking if the secondary is active or not make no sense.
The second one is that it does not react to the server availability. Other drivers periodically check if the primary is available, if not they look for the new primary, if any, and then eventually send an error message. In our case nothing of these actions are taken, and, if the primary is disconnected, you have to reconnect through a `db.close() ` and `db.open() `again.
Unfortunately I have a few time in this period, but this is definetely the next development I would like to do.

**Comment by giorgiofran** [comment]
> If I read you right (puns intended), it's not just the functionality of isConnected, but the entire hot-backup of the secondary servers is basically useless (as a backup) because the entire driver will deem the system as 'down' even if multiple secondary servers are ok.

Yes, all request are alway redirected to the primary (obviously in a replica set).
So, the only thing that you can do is to check the `db.isConnected` getter and, if false, try to reconnect (`db.close();` `db.oepn();`)

**Comment by natgross** [comment]
> Yes, all request are alway redirected to the primary (obviously in a replica set).
> So, the only thing that you can do is to check the db.isConnected getter and, if false, try to reconnect (db.close(); db.open();)
Oh. So the system WILL continue to function ok (after the .close() and .open()) even if the original primary is still down, because a secondary has now become a primary?

**Comment by natgross** [comment]
That is just fine for me (although I have to close and open). 
Question: Is there a call to get the ip of the current primary?

**Comment by giorgiofran** [comment]
You can try with the hello command, but I don't remid if it returns the ip or the url of the primary

**Comment by giorgiofran** [comment]
Otherwise you could check the master connection, ex:
`db.masterConnection.serverStatus.host;`

**Comment by giorgiofran** [comment]
Could you get the problem of the failover?

**Comment by natgross** [comment]
When I shut the primary server, a Windows 10 mongo service, I can't access the database, even after rebooting the client/app. If I try to connect directly to a secondary server (running on Linux), the mongo returns an error that it's not a primary. 
(I don't think this is related to your driver, however.)

**Comment by natgross** [comment]
Is it possible that the my mongodb url is missing something? Here it is:
`mongodb://192.168.1.36,192.168.1.83,192.168.1.84/EZSystem/?replicaSet=replSetEzOne`
The primary is the first ip in the string, and is a Windows 10 machine. The others are running Linux.

**Comment by giorgiofran** [comment]
mongodb://127.0.0.1:27017/EZSystem?replicaSet=replSetEzOne

**Comment by natgross** [comment]
Oh, wow. Time to retest everything.

**Comment by giorgiofran** [comment]
Hope everything is OK, I close this issue.
