### ISSUE TITLE
MongoDart Error: Sort exceeded memory limit of 104857600 bytes, but did not opt in to external sorting

### ISSUE THREAD

**Issue by insinfo** [mongo-dart/mongo_dart#273]
I'm getting this error when accessing a collection with 217 thousand items

```console
MongoDart Error: Sort exceeded memory limit of 104857600 bytes, but did not opt in to external sorting. #0      ModernCursor.nextObject (package:mongo_dart/src/database/cursor/modern_cursor.dart:221:7)\n<asynchronous suspension>\n#1      ModernCursor.stream.readNext (package:mongo_dart/src/database/cursor/modern_cursor.dart:275:21)\n<asynchronous suspension>\n

```

**Comment by giorgiofran** [comment]
This is a message coming from the server.
Give a look to the following:
[sort-exceeded-memory-limit error](https://www.mongodb.com/community/forums/t/sort-exceeded-memory-limit/16093)

**Comment by insinfo** [comment]
Thanks for the quick response, I managed to solve it by changing the configuration file /etc/mongod.conf
I added these lines:
```
setParameter:
    internalQueryMaxBlockingSortMemoryUsageBytes: 335544320
```

then I saw that it had the "allowDiskUse" option:

```
   final cursor = db.collection('vaccinated').modernAggregate(query,
         aggregateOptions: AggregateOptions(allowDiskUse: true));

```

**Comment by giorgiofran** [comment]
I'm closing the issue, feel free to reopen it if needed.
