### ISSUE TITLE
error: The $changeStream stage is only supported on replica sets

### ISSUE THREAD

**Issue by robertoltrocha** [mongo-dart/mongo_dart#276]
Hi,
I'm new to MongoDb and I'm getting this error when trying to do a watch(). I saw that it must be something in the string connection with the bank to fix this error, but I didn't find where I should change. Can you help?
Thanks

**Comment by giorgiofran** [comment]
Depends on how you set up your server/s. If you set up a standaloe MongoDb server, you will get that message, if you have a replica set or a sharded environment, then it should work. Please, look at the documentation on the MongoDb site to see how to set up a replica set.

**Comment by giorgiofran** [comment]
I hope that you solved the problem. I do close this issue.
