### ISSUE TITLE
Union With

### ISSUE THREAD

**Issue by Saulmarti** [mongo-dart/mongo_dart#281]
I can't find that have an AggregationStage, is there any way to make a UnionWith with this package?

**Comment by giorgiofran** [comment]
Sorry, I didn't get the question. Colud you please make an example?

**Comment by Saulmarti** [comment]
Sorry, I mean if there is a way to add a stage in AggregationPipelineBuilder for the UnionWith function.
https://www.mongodb.com/docs/manual/reference/operator/aggregation/unionWith/

**Comment by giorgiofran** [comment]
I will, but I cannot do it soon.

**Comment by giorgiofran** [comment]
Please, see 0.8.0-1.0.beta version. Examples are in example/manual/aggregate.

**Comment by giorgiofran** [comment]
I close this issue.
