### ISSUE TITLE
and out of curiosity, what keywords are available for schemas?

### ISSUE THREAD

**Issue by giorgiofran** [mongo-dart/mongo_dart#283]
and out of curiosity, what keywords are available for schemas?

_Originally posted by @tomassasovsky in https://github.com/mongo-dart/mongo_dart/issues/282#issuecomment-1115239052_

Please see the [mongoDb documentation](https://www.mongodb.com/basics/json-schema-examples)

**Comment by tomassasovsky** [comment]
I see [here](https://json-schema.org/draft/2020-12/json-schema-validation.html#rfc.section.6.1.1) that keywords available for types are "null", "boolean", "object", "array", "number", or "string", or "integer".

Do you happen to know which of these should be used for an ObjectId?

**Comment by giorgiofran** [comment]
I'm not sure, but I guess you can try using `bsonType `instead of `type` with:
`
bsonType: "objectId"
`

**Comment by giorgiofran** [comment]
I hope that you have solved the problem. I close this issue, feel free to repoen it if needed.
