### ISSUE TITLE
Error Invalid state: Connection already closed.

### ISSUE THREAD

**Issue by Saulmarti** [mongo-dart/mongo_dart#284]
Every time I execute a query I check that the connection is open and reopen it but after a few minutes I get this error when I execute the DB.open() function:

MongoDB ConnectionException: Invalid state: Connection already closed.

The function:

`
  checkConnection() async {
    if (!DB.isConnected) {
      print('DB to open');
      await DB.close();
      await DB.open();
    }
  }
`

**Comment by giorgiofran** [comment]
I close this issue, feel free to reopen it if needed
