### ISSUE TITLE
Mysterious error - "MongoDart Error: not primary and secondaryOk=false"

### ISSUE THREAD

**Issue by alexobviously** [mongo-dart/mongo_dart#286]
The past few days, I've been running into this error on my prod server. I've not changed any code related to my connection logic since long before it started occurring. I can't find a reliable way to recreate it, and it doesn't happen immediately - it takes at least half a day to appear, and when it does, it happens with all the queries after that.

I don't know for sure if this is a problem with this package, but I assume so since it says MongoDart Error. I couldn't find any reference to this error anywhere in the code though, or in MongoDB docs, so I'd appreciate any hints.

If it makes a difference, I'm running a DigitalOcean app, with my MongoDB on Atlas free tier,.

Thanks for all of your work on this package :)

**Comment by giorgiofran** [comment]
This is an error coming from the server. 
When you start a replica set you have to explicitly set that the secondary servers are enabled for reading (writing is always only on the primary). Maybe that an election has changed which is the primary and which is the secondary in your RS. Unfortunately, at present, mongo_dart is not able to react to these kind of changes and the only way is to close the connection and acquire again a db connection.
[See here.](https://www.mongodb.com/docs/v4.4/reference/method/rs.secondaryOk/)

**Comment by ss-vijayvavdiya** [comment]
It's worked for me, after adding the flag `readPreference=secondary` in the database connection.
