### ISSUE TITLE
type 'ObjectId' is not a subtype of type 'String' of 'value'

### ISSUE THREAD

**Issue by Zopenzop** [mongo-dart/mongo_dart#289]
I am trying to insert a document into my Mongo Database using this package.

Here's my code -
```
  var db = await Db.create(MONGO_CONN_STRING);
  await db.open();
  var coll = db.collection('reports');
  await coll.insertOne({
    "username": "Tom",
    "action": "test",
    "dateTime": "today",
  });
```

I get a runtime error on line 4

`Unhandled Exception: type 'ObjectId' is not a subtype of type 'String' of 'value'`

Is it an issue with the package or is something wrong with my code?

**Comment by giorgiofran** [comment]
I close this issue, feel free to reopen it if needed.

**Comment by Zopenzop** [comment]
Tested the same piece of code after a long time and surprisingly, it's working just fine now! Without a single change!
