### ISSUE TITLE
Drop index missing

### ISSUE THREAD

**Issue by matisiekpl** [mongo-dart/mongo_dart#290]
Hello.
I really appreciate this library, but I can't find dropIndex method. Are there any plans to do the implementation?

Have a nice day,
Mateusz W.

**Comment by giorgiofran** [comment]
No plans, but it should be not so difficoult to do.
I'm quite busy in this period, but I'l try to provide a solution in the next weeks.

**Comment by giorgiofran** [comment]
Release 0.8.0 comprehends also the dropIndex command.

**Comment by giorgiofran** [comment]
I close this issue, feel free to reopen it if needed
