### ISSUE TITLE
How to use watch()

### ISSUE THREAD

**Issue by dmrcierhn** [mongo-dart/mongo_dart#295]
Hello, I'm trying to use watch() method with streamBuilder but I couldn't so is there a way to use with streamBuilder?

Thanks for your help!

**Comment by giorgiofran** [comment]
What do you mean exactly? May you please provide an example?

**Comment by dmrcierhn** [comment]
In short I want to listen a stream then I want to improve and create a simple chat app

**Comment by giorgiofran** [comment]
Try to first give a look to the examples in the [example/manua/watch folder on github](https://github.com/mongo-dart/mongo_dart/tree/main/example/manual/watch).

**Comment by giorgiofran** [comment]
Did the examples help you? Can we close this issue?

**Comment by giorgiofran** [comment]
Hope you solved your problem. I close the issue.
