### ISSUE TITLE
no host to route

### ISSUE THREAD

**Issue by ysyfff** [mongo-dart/mongo_dart#296]
Code:

<img width="667" alt="image" src="https://user-images.githubusercontent.com/2571290/187991859-dc1ce27a-98d4-4d14-ab02-cfeb243a8900.png">

Error Message:

<img width="772" alt="image" src="https://user-images.githubusercontent.com/2571290/187992789-6d4ddd07-ee90-4465-8514-bcae528bf200.png">

The schema is `mongodb+srv://<username>:<password>@braveyin.v1u6pcp.mongodb.net/swimming` and it can can be opened in MongoDB Compass，while has this error in flutter. That is weird.

**Comment by giorgiofran** [comment]
It is probably an address problem. mongo_dart uses the package `basic_utils` to resolve the address of type `mongodb+srv://` so, I'm not able to tell you which is exactly the problem. you may tray to ask to the `basic_utils` package maintainers if they can help you.

**Comment by giorgiofran** [comment]
Could you solve your problem?

**Comment by giorgiofran** [comment]
I close this issue, feel free to reopen it if needed.
