### ISSUE TITLE
MongoDB

### ISSUE THREAD

**Issue by AleAsc27** [mongo-dart/mongo_dart#300]
Is compatible with MongoDB version 6.x ?
It seems to work fine with version 5.x but not with 6.x

**Comment by giorgiofran** [comment]
It is not complety compatible with 6.x. I'm working on it. Which method is giving you problem? Eventually I could publish a dev version.

**Comment by giorgiofran** [comment]
Release 0.8.0 should be 6.0 frineldy. Please, give it a try and let me know if you run into any problems.
