### ISSUE TITLE
What function can I get the `String` in `ObjectId` when using `find()`?

### ISSUE THREAD

**Issue by SittiphanSittisak** [mongo-dart/mongo_dart#306]
I want to replace the '_id' value (ObjectId) with the `ObjectId.$oid`.
I am using:
```
List<Map<String, dynamic>> data = await mongodb.dbCollection.find().toList();
      for (var i = 0; i < data.length; i++) {
        data[i]['_id'] = (data[i]['_id'] as ObjectId).$oid;
      }
```
but this looks like not good practice.
Are there any functions in `find()` to solve it?

**Comment by giorgiofran** [comment]
You canno substitute the `_id `field, once assigned it cannot be changed. You have to create a new record with the same data and the new key and delete the old one.

**Comment by SittiphanSittisak** [comment]
Hi @giorgiofran, I want to send data via an API with the Map that contains `{ '_id' :  (data[i]['_id'] as ObjectId).$oid }` (the value type is String) not `{ '_id' :  data[i]['_id'] }` (the value type is ObjectId). (Not change data in the database)
At the moment I must use a loop to change this. Is any way without using a loop?

**Comment by giorgiofran** [comment]
I'd do the same way you did.

**Comment by SittiphanSittisak** [comment]
Thank you @giorgiofran . This clear.
