### ISSUE TITLE
Can I create unique index based on a field?

### ISSUE THREAD

**Issue by SittiphanSittisak** [mongo-dart/mongo_dart#307]
My collection is the `user`. The `user` collection has the `company` and `email` fields.
The `email` field is a unique index based on the `company` field.
(The users in the same company can't have email duplicates)
(1 email can create a user for each company)

How to do that?

**Comment by giorgiofran** [comment]
```dart
await collection.createIndex(keys: {'company' : 1, 'email' : 1}, unique: true);
```

**Comment by SittiphanSittisak** [comment]
Thank you so much.
