### ISSUE TITLE
Can't using the `findAndModify` to update specific field.

### ISSUE THREAD

**Issue by SittiphanSittisak** [mongo-dart/mongo_dart#308]
The result always be null from this code:
```
  Map<String, dynamic> data = await mongodb.dbCollection.findAndModify(
    update: [
      {'field A': 'data A'},
      {'field B': 'data B'},
    ],
    query: where.id(ObjectId.parse('Object Id')),
    returnNew: true,
  );
```
but it works with this code. But I don't want to replace the document:
```
  Map<String, dynamic> data = await mongodb.dbCollection.findAndModify(
    update: {'field A': 'data A', 'field B': 'data B'},
    query: where.id(ObjectId.parse('Object Id')),
    returnNew: true,
  );
```
I get an error `Exception: Not implemented for ModifierBuilder({$set: {field A: data A}})` 
When I try using `modify.set` like this:
```
  Map<String, dynamic> data = await mongodb.dbCollection.findAndModify(
    update: [
      modify.set('field A', 'data A'),
      modify.set('field B', 'data B'),
    ],
    query: where.id(ObjectId.parse('Object Id')),
    returnNew: true,
  );
```

What do I mistake?

**Comment by giorgiofran** [comment]
Please, give a look to the [update field](https://www.mongodb.com/docs/manual/reference/command/findAndModify/)

![immagine](https://user-images.githubusercontent.com/4466457/203326816-da144449-6a6e-4fe1-aa6e-e9f085805fe3.png)

**Comment by SittiphanSittisak** [comment]
Yes, I have seen this. I tried to find an example of using an Aggregation Pipeline in `dart` or `mongo_dart`.
The search result has one example as the image below.
![image](https://user-images.githubusercontent.com/59549741/203443221-9bf1bd7c-a1f6-472a-b3bc-162301be8405.png)

After you answer me. I give up and try to copy the template code from the doc.
```
db.students.updateOne( { _id: 3 }, [ { $set: { "test3": 98, modified: "$$NOW"} } ] )
```
Implement this for my code:
```
  Map<String, dynamic> data = await mongodb.dbCollection.findAndModify(
    update: [
         {
             '\$set': {
               'field A': 'data A',
               'field B': 'data B',
             }
         }
    ],
    query: where.id(ObjectId.parse('Object Id')),
    returnNew: true,
  );
```
And it works now.
I thought there was a specific style for the dart but not.

**Comment by SittiphanSittisak** [comment]
Yes, I have seen this. I tried to find an example of using an Aggregation Pipeline in `dart` or `mongo_dart`.
The search result has one example as the image below.
![image](https://user-images.githubusercontent.com/59549741/203443221-9bf1bd7c-a1f6-472a-b3bc-162301be8405.png)
And it did not work.
After this, I give up and try to copy the template code from the doc.
```
db.students.updateOne( { _id: 3 }, [ { $set: { "test3": 98, modified: "$$NOW"} } ] )
```
Implement this for my code:
```
  Map<String, dynamic> data = await mongodb.dbCollection.findAndModify(
    update: [
         {
             '\$set': {
               'field A': 'data A',
               'field B': 'data B',
             }
         }
    ],
    query: where.id(ObjectId.parse('Object Id')),
    returnNew: true,
  );
```
And it works now.
I thought there was a specific style for the dart but not.

**Comment by SittiphanSittisak** [comment]
Yes, I have seen this.
I tried to find an example of using an Aggregation Pipeline in `dart` or `mongo_dart`.
The search result has one example as the image below.
![image](https://user-images.githubusercontent.com/59549741/203443221-9bf1bd7c-a1f6-472a-b3bc-162301be8405.png)
And I tried with code from the doc as below.
```
db.students.updateOne( { _id: 3 }, [ { $set: { "test3": 98, modified: "$$NOW"} } ] )
```

Now, I find the solution that works for `mongo_dart`:
first:
```
  Map<String, dynamic> data = await mongodb.dbCollection.findAndModify(
    update: (AggregationPipelineBuilder()
          ..addStage(SetStage({
            'field A': 'data A',
            'field B': 'data B',
          }))).build(),
    query: where.id(ObjectId.parse('Object Id')),
    returnNew: true,
  );
```
second:
```
  Map<String, dynamic> data = await mongodb.dbCollection.findAndModify(
    update: [
         {
             '\$set': {
               'field A': 'data A',
               'field B': 'data B',
             }
         }
    ],
    query: where.id(ObjectId.parse('Object Id')),
    returnNew: true,
  );
```
