### ISSUE TITLE
How to use the bracket and a multi `or` statement?

### ISSUE THREAD

**Issue by SittiphanSittisak** [mongo-dart/mongo_dart#310]
I want to find with using this statement:
`SELECT * FROM 'form' WHERE 'A' = 'a' AND 'B' = 'b' AND ( 'C' = 'c' OR 'D' = 'd' )`

But this is not working with this the SelectorBuilder:
```
where.eq('A', 'a').and(where.eq('B', 'b').or(where.eq('C', 'c').or(where.eq('D', 'd')))),
```

This seems like this:
`WHERE 'A' = 'a' AND 'B' = 'b' OR 'C' = 'c' OR 'D' = 'd'`

For the `.or` function, this seems after the first statement is always `and`.
```
where.eq('A', 'a').and(where.eq('B', 'b').or(where.eq('C', 'c').eq('D', 'd')))
```
This seems like this:
`WHERE 'A' = 'a' AND 'B' = 'b' OR 'C' = 'c' AND 'D' = 'd'`
Then I must use `.or` every time I want to use the `or` statement.

I want a function that can make the statement like 
`... AND ( ... OR ... OR ... OR ... )`
`where.eq( ... ).andBracket( whereMultiOr.eq( ... ).eq( ... ) )`

How to do that?

**Comment by giorgiofran** [comment]
try this
```dart
where
      .eq('A', 'a')
      .eq('B', 'b')
      .and(where.eq('C', 'c').or(where.eq('D', 'd')));
```

**Comment by SittiphanSittisak** [comment]
Thank @giorgiofran so much.
