### ISSUE TITLE
How to insert data in the `List` field and remove specific data in this?

### ISSUE THREAD

**Issue by SittiphanSittisak** [mongo-dart/mongo_dart#312]
My document is `form`. The `form` has a `commentList` field. The `commentList` field is a list of the `comment` document in the form `Map` type.
Example:
```
Map form = {
  '_id': ObjectId(),
  'commentList': [
    {
      '_id': ObjectId(),
      'comment': 'comment',
      'commentBy': 'commentBy',
      'commentDate': DateTime.now(),
    },
  ],
};
```
I don't know how to insert a `comment` in the `commentList`. Is it possible?
If cannot insert this, some invalid process will occur when users comment at the same time(or remove the comment).

Another choice is creating a `comment` collection. But I need to search the `comment` collection when I search the `form`.

Can we do this? 
Is using `commentList` a bad idea?
Should I use the `comment` collection?

**Comment by giorgiofran** [comment]
In general mongo_dart replicates the mongosh behavior.
If you give a look to the [MongoDb manual you can see](https://www.mongodb.com/docs/manual/reference/operator/update/push/):
![immagine](https://user-images.githubusercontent.com/4466457/205091986-442c81ee-1deb-4358-b1df-04abf84c7e36.png)

**Comment by SittiphanSittisak** [comment]
Thank @giorgiofran for your info.
I have seen designing the schema on youtube.
I shouldn't collect the `comment` collection as a `commentList` field in the `form` collection because each document has a limited size(16 MB) and this `commentList` field can become too big.
