### ISSUE TITLE
Regression in 0.8.1 `Db is in the wrong state: State.OPENING`

### ISSUE THREAD

**Issue by SunlightBro** [mongo-dart/mongo_dart#313]
Calling `await Db(uriString).open(secure: true);`

- in 0.7.4+1 connects successfully
- in 0.8.1 throws `MongoDart Error: Db is in the wrong state: State.OPENING`

<details>
  <summary>Stack trace</summary>
  <p>

```sh
#0      Db._masterConnectionVerified (package:mongo_dart/src/database/db.dart:211:7)
#1      Db.masterConnection (package:mongo_dart/src/database/db.dart:281:38)
#2      Db.getNonce (package:mongo_dart/src/database/db.dart:595:9)
#3      MongoDbCRAuthenticator.authenticate (package:mongo_dart/src/auth/mongodb_cr_authenticator.dart:18:15)
#4      Db.authenticate (package:mongo_dart/src/database/db.dart:737:25)
#5      ConnectionManager._connect (package:mongo_dart/src/network/connection_manager.dart:97:18)
<asynchronous suspension>
#6      ConnectionManager.open (package:mongo_dart/src/network/connection_manager.dart:141:9)
<asynchronous suspension>
#7      Db.open (package:mongo_dart/src/database/db.dart:481:7)
<asynchronous suspension>
```
  </p>
</details>

I'm have a Azure Cosmos Db , with a specific Table I'm trying to connect to, using authMechanism=MONGODB-CR
`mongodb://foo-bar:******@foo-bar.mongo.cosmos.azure.com:<mongoDbPort>/<mongoDbTable>?authMechanism=MONGODB-CR`

**Comment by giorgiofran** [comment]
I released 0.8.2 with a fix. Please, give it a try and let me know if it is OK.

**Comment by DevMensIT** [comment]
i'm also getting same error on 0.9.1 version 
`MongoDart Error: Attempt to open db in state State.OPENING`

**Comment by giorgiofran** [comment]
May you please give more details?
Which method are you using to create the Db?
Which version of MongoDb?
Thanks

**Comment by DevMensIT** [comment]
> May you please give more details? Which method are you using to create the Db? Which version of MongoDb? Thanks

Actually problem is im using provider continue refresh data from mongodb while inserting i'm getting that error [only happen when connection state is opening sometime its gets inserted record] :

 ```
await db.open().then((value) async {
        await collection.insert(data);
        notifyListeners();
      }).catchError((error) {
        print('Error connecting to MongoDB: $error');
      });
```

i'm now looking for another solution where database stay open always 
do you have solution regarding that ?

**Comment by giorgiofran** [comment]
Normally you maintain the same Db object.
once that it has been opened, you reuse the same, unless it gets disconnected.
In this case you have to close the Db and reopen again (or create a new one).
When you are done with all the operations you can close the Db.

In the folder example of the sources there are many examples.

``` Dart
 var db = Db(defaultUri);
 await db.open();

 var collectionName = <Collection Name>;
 var collection = db.collection(collectionName);
  ...
 await db.close();
  
```

**Comment by DevMensIT** [comment]
> Normally you maintain the same Db object. once that it has been opened, you reuse the same, unless it gets disconnected. In this case you have to close the Db and reopen again (or create a new one). When you are done with all the operations you can close the Db.
> 
> In the folder example of the sources there are many examples.
> 
> ```dart
>  var db = Db(defaultUri);
>  await db.open();
> 
>  var collectionName = <Collection Name>;
>  var collection = db.collection(collectionName);
>   ...
>  await db.close();
>   
> ```

actually i'm trying to keep open my database connection using provider so it keep fetching data but problem is when i'm trying to insert data sometime its give me error and record not getting insert because of this error  : `MongoDart Error: Db is in the wrong state: State.OPENING`

do you have any other solution for that  ? i just want to  keep live records  fetch

**Comment by giorgiofran** [comment]
What is "provider"?

**Comment by DevMensIT** [comment]
> What is "provider"?

provider is state management.

**Comment by giorgiofran** [comment]
Can you give me an example?
