### ISSUE TITLE
Creating file with GridFS not working

### ISSUE THREAD

**Issue by busslina** [mongo-dart/mongo_dart#319]
I have latest version of mongo_dart (^0.8.2). 

My code is:
```
print('Saving file in MongoDB');
final bucket = await Modules.mongoDB.imagesGridFsBucket;
final fileStream = file.openRead();
final gridIn = bucket.createFile(fileStream, 'photo.png');
final saved = await gridIn.save();
print('Saved: $saved');
```

The output is:

> Saving file in MongoDB
> Saved: {ok: 0.0, errmsg: getLastError command is not supported, code: 5739000, codeName: Location5739000}

**Comment by giorgiofran** [comment]
I have uploaded the version 0.9.0. It should solve your problem. Please, test it and let me know.

**Comment by busslina** [comment]
Now it works fine. Thank you!

> Saving file in MongoDB
> Saved: {n: 1, ok: 1.0}
