### ISSUE TITLE
Find by word

### ISSUE THREAD

**Issue by marcellocamara** [mongo-dart/mongo_dart#326]
I'm trying to achieve this:
![image](https://user-images.githubusercontent.com/18273071/225993481-ec059d0e-ceca-4077-bdf4-52651f19392c.png)

Find any name field wich matches my word
If I search for "a" brings all names that contains the char "a".

This don't work:
```
    return await collection
        .find(where.eq('name', '/$name/i').sortBy('name'))
        .toList();
```

I didn't found any documentation about it on mongo_dart.
All the find methods don't have documentation on this package, and I don't know what they do :(

**Comment by JohnF17** [comment]
Hi, seams easy to deal with so here's what I've came up with. (_Please mind that I am nowhere near any of my equipment to test this, so i'm not entirely sure if it works or not but give it a try_)

```
var res = await collection.modernFind(filter: {
  'name': {'$name/i'}
}, sort: {
  'name': 1
}).toList();
```
_If it doesn't work, i'll do tests, fix it up and send a working method, if others have the answer or in fact just a better method, do share._

**Comment by marcellocamara** [comment]
Thanks, @JohnF17 

This worked:
```
collection.find(where.match('name', word)
  .sortBy('name'))
  .toList();
```

I'm thinking if there is any problem to do this regex on the DB for every search coming from the origin
I've already created an index search for it, but this is my first time developing the backend and looking for the best practice

**Comment by JohnF17** [comment]
Ahh wonderful 🙂, glad it worked for ya @marcellocamara .

> I'm thinking if there is any problem to do this regex on the DB for every search coming from the origin

I'd say it depends (_leaning more towards the negative effects though_), I mean think about it, each call to the `find` method can consume system resources, including memory, CPU, and cause latency for IOPS. If the application is **heavily used** or **has many concurrent users**, these resources can quickly become a **bottleneck**, which can cause performance issues and potentially even crashes or other errors. 😕
Not to mention, the significant performance degradation, especially if the underlying database collections are large. Each call to the `find` method requires the database to execute a query, which can also be **time-consuming** depending on the user's connection speeds and/or **your database server's performance**.
Now of course, there are somethings you can do to counter that and reduce the risk of that much negative effects so long as you **maintain the DB connection state** open (i.e _by using a singleton class design pattern_) or as you have mentioned **having a well-built indexing mechanism helps**. But i'd be a bit more cautious when implementing this type of searching especially if you'd expect a large audience using it.
