### ISSUE TITLE
Is mongo_dart have a function for update without specific field for the object type

### ISSUE THREAD

**Issue by SittiphanSittisak** [mongo-dart/mongo_dart#331]
ex.
The collection user has fields including _id, username, name, and address.
An address field is an object that has fields including number,  road, and content.
I want to update the name and address fields without the content field in the address field.
```
  final ModifierBuilder modifierBuilder = modify;
  if (name != null) modifierBuilder.set('name', name);
  if (address != null) modifierBuilder.set('address', address);
  final WriteResult writeResult = await mongodbCollection.updateOne(where.id(id), modifierBuilder);
```
Is mongo_dart have any function to do that like `modifierBuilder.set('address', address).without('address.content');`?

In an actual situation, it will be more complex than this example. So, it will not be easy to read and extra lines for any object if using the `Project` with `AggregationStage` like
```
      final AggregationStage stage = Project({
        '_id': 1,
        'username': 1,
        'name': name== null ? 1 : '\$$name',
        'address.number':  address.number== null ? 1 : '\$${address.number}',
        'address.road': address.road == null ? 1 : '\$${address.road}',
        'address.content: 1,
      });
```

**Comment by giorgiofran** [comment]
I have not clear what you would like to do. May you please give an example of the document before the update and how you would like it to be after the update?

**Comment by SittiphanSittisak** [comment]
assume the doc of the user collection is:
```
class Address {
  String? number;
  String? road;
  String? soi;
  String? content;
// another fields
}
```
The address class is:
```
class Company {
  ObjectId? id;
  String? name;
  String? taxNumber;
  String? imageLogoPath;
  Address? address;
// another fields
}
```
Some fields in the company collection were received from the main server including name, taxNumber, and address.content.
These fields are reserved. (Not allowed to edit)
I want to create an API that is updating the company profile like:
```
Future<Object> updateCompany(ObjectId id, {String? imageLogoPath, Map? address}) async {
  final ModifierBuilder modifierBuilder = modify;
  modifierBuilder.set('imageLogoPath', imageLogoPath);
  modifierBuilder.set('address', address);
  final WriteResult writeResult = await mongodbCollection.updateOne(where.id(id), modifierBuilder);
}
```
but `modifierBuilder.set('address', address);` will replace the address.content(reserved field).
Is there any function in the `ModifierBuilder` class to block updating of a specific field like:
```
modifierBuilder.setWithOut(['address.content']);
```

**Comment by giorgiofran** [comment]
Thanks for the clarification. Now I got the requirement.
There is no such an operator in MongoDb also. As you know we base our functions on MongoDb operators. The only solution that I see is to update the address fields one by one, excluding the content one.
You can do this using the embedded notation like "`address.number`".
see [here](https://www.mongodb.com/docs/manual/reference/operator/update/set/#set-fields-in-embedded-documents)
The other solution, but maybe it not depends on you, is to redesign the classes, separating the content field from the address, or creating a super class like FullAddres that contains the Address plus the content field, or something like that.

**Comment by SittiphanSittisak** [comment]
Thank you. I agree, I will use the embedded notation.
