### ISSUE TITLE
Is there a function to check the SelectorBuilder that is empty or not?

### ISSUE THREAD

**Issue by SittiphanSittisak** [mongo-dart/mongo_dart#335]
Example
```
final SelectorBuilder selectorBuilder = where;
    if (status != null) selectorBuilder.eq('status' , status);
    if (keyWord != null) selectorBuilder.and(where.match(name , keyWord).or(where.match(idCard , keyWord)));
```
For this example, if the status is null and keyWord isn't, the error will occur with `Bad state: `And` operation is not supported on empty query`.
Is there a parameter to check the SelectorBuilder that is empty or not?
I will use this like `!selectorBuilder.isQueryEmpty ? .... : ....` or `selectorBuilder.countQuery == 0 ? .... : ....`.

Actually, I can handle it with basic code like
```
final SelectorBuilder selectorBuilder = where;
bool isQueryEmpty = true;
    if (status != null) {
       isQueryEmpty = false;
       selectorBuilder.eq('status' , status);
    }
```
or check with `status != null` for using `add` or not.
But is mongo_dart already have this?

**Comment by SittiphanSittisak** [comment]
I found the `.getQueryString()'` function that gives the query in string. This can convert it to a map with jsonDecode.
I check the selectorBuilder with `selectorBuilder.getQueryString() == '{}'`

If mongo_dart doesn't have a function to check the SelectorBuilder that is empty or not you can close this issue.
But there has a function to do that, suggest me.

**Comment by giorgiofran** [comment]
Sorry, there is no function like that.

**Comment by SittiphanSittisak** [comment]
It's ok.
This function doesn't need. Many solutions can make it work.
