### ISSUE TITLE
each element is missing for the $addToSet with each

### ISSUE THREAD

**Issue by kishandonga** [mongo-dart/mongo_dart#336]
I'm trying to push an array of elements using $addToSet where I noticed that $each is missing, for more information refer below link and query example.

https://www.mongodb.com/docs/manual/reference/operator/update/addToSet/#std-label-addToSet-modifiers
https://www.mongodb.com/docs/manual/reference/operator/update/each/#mongodb-update-up.-each

Syntax:

`{ $addToSet: { <field>: { $each: [ <value1>, <value2> ... ] } } }`

Example:

```
db.inventory.updateOne(
   { _id: 2 },
   { $addToSet: { tags: { $each: [ "camera", "electronics", "accessories" ] } } }
 )
```

**Comment by giorgiofran** [comment]
Thanks for pointing this out. I will fix it as soon as I have time ...

**Comment by giorgiofran** [comment]
Hi, I forgot this method ;-) but the `addEachToSet` method should solve your problem.

**Comment by kishandonga** [comment]
There is in the current version `mongo_dart: ^0.9.1`

this method is not available as per my understanding, I checked the code as well `ModifierBuilder()` does not have `addEachToSet` method.

**Comment by giorgiofran** [comment]
You are right. This method is in my dev code. I will deploy it in a short time.

**Comment by giorgiofran** [comment]
Please, update your dependencies and check for the new method.

**Comment by kishandonga** [comment]
There is the [mongo_dart](https://pub.dev/packages/mongo_dart) still showing the old version can you check if it is deployed or not? 

Current version `mongo_dart: ^0.9.1` 
Published [4 months ago](https://pub.dev/packages/mongo_dart)

**Comment by giorgiofran** [comment]
The method is defined in the package `mongo_dart_query`. So you should update your dependencies and check that the version 4.0.1 of `mongo_dart_query `is in use.

**Comment by giorgiofran** [comment]
Is it OK? Can I close this issue?

**Comment by kishandonga** [comment]
Yup, sure not an issue but can we publish [mongo_dart](https://pub.dev/packages/mongo_dart) this package again with a new version so other users can access added method easily without the dependency of `mongo_dart_query`

**Comment by kishandonga** [comment]
As of now, it is working fine for me for the above comment you can take it as a suggestion from my side.

**Comment by giorgiofran** [comment]
Thanks, I close this issue.
