### ISSUE TITLE
Find brings some fields

### ISSUE THREAD

**Issue by paulobreim** [mongo-dart/mongo_dart#337]
How do I do a find and bring only a few fields.
I tried for example:

await mycoll.find({name: 1,email:1}).toList(); 
or like mongosh
await mycoll.find({},{email:1})
but dos not works

the fields parameter no longer exists

tks

**Comment by giorgiofran** [comment]
https://github.com/mongo-dart/mongo_dart#find

**Comment by paulobreim** [comment]
Thank you, i made it and works

var result = await collection.find(where.fields(['field1'])).toList();

**Comment by giorgiofran** [comment]
De Nada
