### ISSUE TITLE
Is there a way to modify object inside objects in the database?

### ISSUE THREAD

**Issue by busslina** [mongo-dart/mongo_dart#340]
I have this database entry:
![imagen](https://github.com/mongo-dart/mongo_dart/assets/73592852/4321cc14-4ab9-43b4-8015-57333d89d1b3)

I want to update only one field, E.g., `clientConfigurationBase` > `advices` > `sessionEvents` > `sound`. 

Is it possible to modify only the `sound` entry without updating the whole `clientConfigurationBase` entry?

Thank you

**Comment by giorgiofran** [comment]
Inside the update method use the following Modifier Builder:
 ` modify.set('clientConfigurationBase.advices.sessionEvents.sound', false);`

**Comment by busslina** [comment]
@giorgiofran Thank you. I supose this way is much more efficient
