### ISSUE TITLE
Handling multiple db connections to different databases

### ISSUE THREAD

**Issue by mastermind-computing** [mongo-dart/mongo_dart#343]
Hello everyone to keep it very short I have a project that consists multiple dbs for different customers I dont't have much experience with dart backend so my initial thought was creating a reusable dbMap and implementation was like this

```dart
//Mongo connection utils
class MongoUtils {
  static Map<String, Db> dbMap = {};

  static Future<DbCollection> connection({
    required String collection,
    String dbName = DbConfig.defaultDbName,
  }) async {
    //Check if db is in map
    var dbQuery = MongoUtils.getDb(dbName);

    //Connect if not
    if (dbQuery == null) {
      var db = await MongoUtils.connectToDb(dbName);
      return db.collection(collection);
    }
    return dbQuery.collection(collection);
  }

  static Db? getDb(String dbName) {
    var dbQuery = dbMap[dbName];

    //If db not exist in map return null
    if (dbQuery == null) return null;

    //I am not really sure if this code do something
    //But my intention is creating new db connection
    //if db state is not open
    if (dbQuery.state != State.OPEN) {
      return null;
    }
    return dbQuery;
  }

  static Future<Db> connectToDb(String dbName) async {
    try {
      var db = Db(DbConfig.instance!.getURI(dbName: dbName));
      await db.open();

      //Same here not really sure if this prevents anything
      //or do any good
      if (db.state == State.OPEN) {
        dbMap[dbName] = db;
      }
      return db;
    } catch (e) {
      throw ServerException(code: SharedErrorCode.mongo8888);
    }
  }
}
```

Although it works like %95 of the time some Kubernetes pods loses access to specific dbs for an unknown reason to me so I have to restart them occasionally.How would you approach this problem? What I need is reusable and reliable multiple database connections.For reference the go mongo driver implementation was way easier because you can create a client to whole mongo service without specifying db beforehand but I couldn't find similar approach for mongo-dart but I might have missed some things or two.

Here is the go example without a db map

```go
type handler struct {
	Client *mongo.Client
	D      *dbconfig.DbConfig
}

//H Current handler struct for mongo client
var H *handler

//StartDatabase Starts mongo connection operations
func StartDatabase(ctx context.Context, d *dbconfig.DbConfig) {
  //Some initialization here
}

//GetCompanyCollection Retrieve mongo collection with company database name
func GetCompanyCollection(dbName string, collection string) *mongo.Collection {
	return H.Client.Database(dbName).Collection(collection)
}
```

**Comment by giorgiofran** [comment]
Hi, the actual release of mongo_dart, if you have a replica set, can give some issues when the Db changes the primary connection.
In this case the driver looses the connection and it is not able to reconnect to the new one.
You can check if there is the connection with the isConnected getter.
If there is no connection, you have to close the Db and reopen it again, in order to connect with the new primary.
We are developing, but free time is not so much so it is taking a lot of time, a new version of the driver that will have the concept of client, plus or minus like in the go one. But don't expect to see it soon ... :-(

**Comment by mastermind-computing** [comment]
I will change the dbState == OPEN checks to isConnected ones and hope for the best for now. And yes I am trying to connect to replica set so that might be the issue.Thanks for the response

**Comment by mastermind-computing** [comment]
Yes things are more stable now I think it worked thanks

**Comment by giorgiofran** [comment]
Welcome
