### ISSUE TITLE
MongoDart Error: Regular expression is invalid: missing terminating ] for character class

### ISSUE THREAD

**Issue by SittiphanSittisak** [mongo-dart/mongo_dart#349]
I get this error when use it.
```
mongodb.dbCollection.find(where.match('name', '[')) // any words that contain '['
```

**Comment by giorgiofran** [comment]
Match uses a regular expression. Try "\[". "[" is a special character an needs to be escaped

**Comment by SittiphanSittisak** [comment]
Is there another special character in mongo_dart that I should know?
I can use a sub string every time I use match but is possible to make this handle on this package?

**Comment by giorgiofran** [comment]
This has nothing to do with mongo_dart. It is the Regular Expression syntax. Search in internet the documentation or give a look to the [RegExpr class in dart](https://api.flutter.dev/flutter/dart-core/RegExp-class.html).

**Comment by SittiphanSittisak** [comment]
Thank you, I got it.

**Comment by SittiphanSittisak** [comment]
Hi, for this issue I must use `RegExp.escape` for every keyword that is used for the `.match` method.
If not use this and the keyword contains a character, it will always error.
So, is it possible to add using the `RegExp.escape` in the `.match` method?

like this
```
  SelectorBuilder match(String fieldName, String pattern,
      {bool? multiLine, bool? caseInsensitive, bool? dotAll, bool? extended}) {
    _addExpression(fieldName, {
      '\$regex': BsonRegexp(RegExp.escape(pattern),
          multiLine: multiLine,
          caseInsensitive: caseInsensitive,
          dotAll: dotAll,
          extended: extended)
    });
    return this;
  }
```

**Comment by giorgiofran** [comment]
I have added a new parameter that does what you want. You have to updat the dependencies so that you will use the last version of the mongo_dart_query package.

**Comment by giorgiofran** [comment]
I close this issue, feel free to reopen it if needed.
