### ISSUE TITLE
Transations support?

### ISSUE THREAD

**Issue by busslina** [mongo-dart/mongo_dart#350]
Is transactions feature implemented? Is planned to support that in the future?

https://www.mongodb.com/docs/manual/core/transactions/

**Comment by giorgiofran** [comment]
Transactions are not implemented yet. I'm working on a new version of mongo_dart that will also have transactions, but, unfotunately, I have a few time for develpments, so, it will take time.

**Comment by busslina** [comment]
Thanks

**Comment by bobjackman** [comment]
@giorgiofran when you say "it will take time", should we expect something like a couple weeks? A couple months? A couple years? I only as because we really need transactions, so depending on the answer, we might be better off either changing libs, or rolling our own.

**Comment by giorgiofran** [comment]
Hi @bobjackman , please, consider that I can work on this package only in my free time. The present situation is:
I'm working on a new version of the query api that will be called mongo_db_query and that will be available in alpha version soon, maybe next weekend.
I'm also working on a new version of the driver (mongo_db_driver) with a Mongo client, transactions and more. On this side I'd say that I'm in a pre-alpha stage, as not all the functionalities have been developed yet, but basic CRUD ones are, with transactions.
Now, if you want, I could publish also this pre-alpha version, let's say in one month, but consider that it is in a very early stage and that will need a lot of testing and that it will not be production ready surely before than one year.
Let me know!

**Comment by giorgiofran** [comment]
Hi, I have released a new package called mongo_db_driver that contains also sessions and transactions.
It is still in a development phase (some functionalities missing), but, if would be important to have a feedback.

**Comment by busslina** [comment]
> Hi, I have released a new package called mongo_db_driver that contains also sessions and transactions. It is still in a development phase (some functionalities missing), but, if would be important to have a feedback.

Lately I have been using PostgreSQL instead of MongoDB, but as soon as I come back to it I will try to give some feedback :)
