### ISSUE TITLE
listDatabases does not work

### ISSUE THREAD

**Issue by TimeLord2010** [mongo-dart/mongo_dart#352]
I have a [guess of whats the cause](https://github.com/mongo-dart/mongo_dart/issues/304).

The method hangs and does not throw error properly too. I had to enable catch All Exception to even see it:
 
![Screenshot 2023-12-16 at 20 35 09](https://github.com/mongo-dart/mongo_dart/assets/50129092/dc980446-4d4a-4e70-82b6-d682848970ed)

Now, the other problem, arguably, is that returning a List<dynamic> is not ideal. 

I'm open to help by making a pull request, but I need to know how you feel about these points.

**Comment by giorgiofran** [comment]
Yes, the cause is what you supposed.
ListDatabases does not work on recent releases of MongoDB
You could do something like the following:
```Dart

import 'package:mongo_dart/mongo_dart.dart';
import 'package:mongo_dart/src/database/commands/base/db_admin_command_operation.dart';

const dbName = 'mongo-dart-example';
const dbAddress = '127.0.0.1';

const defaultUri = 'mongodb://$dbAddress:27017/$dbName';

void main() async {
  var db = Db(defaultUri);
  await db.open();

  Future cleanupDatabase() async {
    await db.close();
  }

  if (!db.masterConnection.serverCapabilities.supportsOpMsg) {
    return;
  }
  var command = DbAdminCommandOperation(db, {'listDatabases': 1});
  var ret = await command.execute();
  print(ret);

  await cleanupDatabase();
}

```
For hints about the command [see here](https://www.mongodb.com/docs/manual/reference/command/listDatabases/#mongodb-dbcommand-dbcmd.listDatabases).

**Comment by TimeLord2010** [comment]
Thank you for your time.
