### ISSUE TITLE
Are there any plans to support Listening to changes ? like a Wach()

### ISSUE THREAD

**Issue by Emmanuelfrimpong** [mongo-dart/mongo_dart#355]
MongoDB has the capability to listen to changes in a collection. Are there any plans to add this feature?

**Comment by giorgiofran** [comment]
It is already in place..

**Comment by Emmanuelfrimpong** [comment]
Thanks for your reply.
I have not seen anything like that in the documentation, can you please
point met to where I can find some information about that implementation?
Thank you

**Comment by Emmanuelfrimpong** [comment]
just found it
