### ISSUE TITLE
Realtime data access

### ISSUE THREAD

**Issue by theseriouscoder123** [mongo-dart/mongo_dart#356]
I am new to using this library and mongo db as a whole. I am trying to build an app in which I require realtime display of data, I tried the following code:-
To fetch data:-
```
  static Stream<Map<String, dynamic>> getRealOrders() {
    return db!.collection("orders").find();
  }
```
To display data:-
```
StreamBuilder(
          stream: MongoApi.getRealOrders(),
          builder: (context, snapshot) {
            if (snapshot.connectionState == ConnectionState.waiting) {
              return const Center(
                child: CircularProgressIndicator(),
              );
            }
            if (snapshot.data== null) {
              return const Center(
                child: Text("No Pending Orders"),
              );
            }
            return ListView.builder(
              itemCount: snapshot.data!.length,
              itemBuilder: (context, index) {
                return Text(snapshot.data!["placed_on"]);
              },
            );
          },
        ),
```
However this is not working and the new element is displayed only after hot reloading the app also this code repeats the element to the number of fields in the data element. How can I achieve my desired result which is to display a list of all the elements and it has real-time updation. Also I tried calling forEach method on the results of find() which displays the list properly however does not have real-time updation

**Comment by giorgiofran** [comment]
Hi, I'm not a flutter expert, anyway, the `find()` method returns the list at the moment in which you run the request. If you want to be uodated on subsequent changes, you have to use the `watch() `method. An example on how to use `watch()` is available in the example folder in github.

**Comment by theseriouscoder123** [comment]
> Hi, I'm not a flutter expert, anyway, the `find()` method returns the list at the moment in which you run the request. If you want to be uodated on subsequent changes, you have to use the `watch() `method. An example on how to use `watch()` is available in the example folder in github.

**Comment by theseriouscoder123** [comment]
Thank you got it workin
