### ISSUE TITLE
Connection String Error (SocketError)

### ISSUE THREAD

**Issue by Andrewaziz99** [mongo-dart/mongo_dart#359]
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: ClientException with SocketException: Connection timed out (OS Error: Connection timed out, errno = 110), address = dns.google.com, port = 39830, uri=https://dns.google.com/resolve?name=clouddb.gifwimn.mongodb.net&type=16&dnssec=false

This error occured when connecting to mongoDB

This is my code I used:

import 'package:mongo_dart/mongo_dart.dart';

import 'dart:developer';
import 'package:mongo_dart/mongo_dart.dart';
import 'package:flutter_dotenv/flutter_dotenv.dart';

var host = dotenv.env['MONGO_HOST']; //clouddb.gifwimn.mongodb.net
var user = dotenv.env['MONGO_USER'];
var password = dotenv.env['MONGO_PASS'];

class MongoDB {
  static var db, userCollection;

  static connect() async {
    print("Connecting to MongoDB...");
    db = await Db.create('mongodb+srv://$user:$password@$host/clouddb?retryWrites=true&w=majority');
    await db.open();
    print('Connected to MongoDB');
    inspect(db);
    userCollection = db.collection('users');
  }

  static Future<List<Map<String, dynamic>>> getUsers() async {
    var users = await userCollection.find().toList();
    return users;
  }

}

**Comment by giorgiofran** [comment]
To resolve the address, the driver tries to connect to a google service. Probably it was down at that moment. Did you retry yet?

**Comment by Andrewaziz99** [comment]
> To resolve the address, the driver tries to connect to a google service. Probably it was down at that moment. Did you retry yet?

I already tried a lot to connect but the same error occured

**Comment by Ahmadre** [comment]
> > To resolve the address, the driver tries to connect to a google service. Probably it was down at that moment. Did you retry yet?
> 
> 
> 
> I already tried a lot to connect but the same error occured

This is a network access error and has nothing to do with this package.

You have to accept your IP-address or access from anywhere (0.0.0.0). But make sure you're securely connecting to your database, otherwise I would recommend using a VPC connection and give Mongo that IP Address of the VPC connection if you use Google Services.

**Comment by giorgiofran** [comment]
Could you solve the issue?

**Comment by giorgiofran** [comment]
Hope you solved the problem. I close this issue.
