### ISSUE TITLE
How do I update all docs, insert them if doc don't exist, and remove the rest of the docs?

### ISSUE THREAD

**Issue by SittiphanSittisak** [mongo-dart/mongo_dart#360]
I have a doc with these fields.
```
- _id
- companyId
- name
- dataList
```
This doc can be updated, inserted, and deleted at one time.
For example.
current docs are
```
{ '_id': ...., 'companyId': c1, name: n1, dataList: [1,2,3,4,5] }
{ '_id': ...., 'companyId': c1, name: n2, dataList: [6,7,8,9,10] }
```
Users load this data and add, edit, and delete some docs then click save.
The data that the user sends to the server is:
```
{ '_id': ...., 'companyId': c1, name: n1, dataList: [0,1,2,3,4] }
{ '_id': ...., 'companyId': c1, name: N1, dataList: [0,-1,-2,-3,-4] }
{ '_id': ...., 'companyId': c1, name: b1, dataList: [5] }
```

At this moment I do it by:
```
final WriteResult removeResult = await mongodb.dbCollection.deleteMany(where.eq('type', type).eq('companyId', companyId));
if (!removeResult.isSuccess) return false;
final BulkWriteResult insertResult = await mongodb.dbCollection.insertMany(docList);
```
But it will fail if the insertion fails (Assume any insertion always fails).
It will be fine if the transaction is available but it's not.
So I need to do these at the same time. Can we do this?

**Comment by giorgiofran** [comment]
What I can suggest is to update the DB at any change that the user does.

**Comment by giorgiofran** [comment]
Did you find a solution?

**Comment by SittiphanSittisak** [comment]
Sorry, I changed the entity and the solution of my work.
So I don't find a solution for this. Thank you for working.
