### ISSUE TITLE
Unable to Connect to MongoDB Instance Hosted on AWS EC2 from Flutter

### ISSUE THREAD

**Issue by zohaib304** [mongo-dart/mongo_dart#369]
When attempting to connect to the MongoDB instance using the mongo_dart package in Flutter, I receive the following error:

```
MongoDB ConnectionException: Could not connect to [MongoDB_IP]:27017
- HandshakeException: Connection terminated during handshake
```
`Connection String: mongodb://username:<password>@<ip>:27017/testdb
`

MongoDB Compass successfully connects to the MongoDB instance using the same connection string.

I would appreciate any guidance or assistance. Thank you

**Comment by giorgiofran** [comment]
It is difficult to say.
Try to do a simple dart program (no flutter) and see what happens.
Give a look also to [this](https://github.com/flutter/flutter/issues/133704).

**Comment by zohaib304** [comment]
I've tried running a simple Dart program without using Flutter, and everything seems to be working fine.
