### ISSUE TITLE
type '_Set<String>' is not a subtype of type 'Map<dynamic, dynamic>?' in type cast

### ISSUE THREAD

**Issue by luoyi58624** [mongo-dart/mongo_dart#370]
<img width="1139" alt="image" src="https://github.com/mongo-dart/mongo_dart/assets/46178521/cb9631a7-1c1f-4a2f-93c0-5b476799ad63">

**Comment by giorgiofran** [comment]
In the remove method you are assign a Set and not a Map, it should be` {'_id': ObjectId.parse('573a1396f29313caabce4a9a')}` (the number is taken from an example ...). More, if the '_id' is an objectId you have to pass to the method an instance of the class `ObjectId`
