### ISSUE TITLE
caseInsensitive: true working as false (v 0.10.x)

### ISSUE THREAD

**Issue by GustavoTru** [mongo-dart/mongo_dart#376]
In this line of code:

lista1 = await wine.distinct(
          'nome', where.match('nome', expressaoBuscar, caseInsensitive: true));
          
 On version 0.10.x the caseInsensitive:true works as false. And false works as true.... 

It works the right way on versions 0.8.x and 0.9.x

**Comment by giorgiofran** [comment]
Fixed

**Comment by giorgiofran** [comment]
Thanks, I close the issue.

**Comment by GustavoTru** [comment]
Thanks Giorgio.

I made a donation to the project, really liked it.

But I don't see any changes... Still working true as false and vice-versa.
Just downloaded the new version....


Gustavo

**Comment by giorgiofran** [comment]
Obrigado pela doação. Try to refresh the dependencies.
