### ISSUE TITLE
Aggregation not working

### ISSUE THREAD

**Issue by jaykukadiya99** [mongo-dart/mongo_dart#379]
I want to perform aggregation and I wrote an aggregation query which works fine in noSqlBooster. but in flutter, it throw an error 

> {ok: 0.0, errmsg: Unsupported OP_QUERY command: aggregate. The client driver may require an upgrade. For more details see https://dochub.mongodb.org/core/legacy-opcode-removal, code: 352, codeName: UnsupportedOpQueryCommand, $clusterTime: {clusterTime: Timestamp(1718285118, 4), signature: {hash: BsonBinary(817ffe455ee2f86854bb839fd77b9923ef05be5b), keyId: 7323440232097906694}}, operationTime: Timestamp(1718285113, 22)}

I am using MongoDb Atlas free tier

Flutter : 3.22
Mongo_dart: 0.10.3

**Comment by giorgiofran** [comment]
May you share a snippet of the code that you are using?

**Comment by jaykukadiya99** [comment]
**Aggregation pipeline**

```
var pipline = AggregationPipelineBuilder()
          .addStage(
            Lookup(
              from: MongoDBCollections.customers,
              localField: 'customerId',
              foreignField: '_id',
              as: 'customer',
            ),
          )
          .addStage(
            Lookup(
              from: MongoDBCollections.products,
              localField: 'productId',
              foreignField: '_id',
              as: 'product',
            ),
          )
          .addStage(
            Unwind(Field('customer')),
          )
          .addStage(
            Unwind(Field('product')),
          )
          .build();


      final res = await MongoApi.aggregate(
          MongoDBCollections.customerSubscriptions, pipline);

      if (res.statusCode == 200) {
        List<CustomerSubscriptionModel> list = [];
        res.data.forEach((v) {

          list.add(CustomerSubscriptionModel.fromJson(v));
        });

        return list;
      } else {
        return [];
      }
```

**Aggregate function**


```
static Future<ResponseModel> aggregate(
      String collectionName, List<Map<String, dynamic>> pipeline) async {
    try {
      final db = MongoConnectionManager().db;
      if (db != null) {
        var collection = db.collection(collectionName);
        var result = await collection.aggregate(pipeline, allowDiskUse: true);
        return ResponseModel.success(result);
      }
      return ResponseModel.error('Error in connection');
    } catch (e) {
      debugPrint('Error in aggregate: $e');
      return ResponseModel.error(e.toString());
    }
  }
```


@giorgiofran

**Comment by giorgiofran** [comment]
Try to use `aggregateToStream` instead
``` dart
var result = await collection.aggregateToStream(pipeline, allowDiskUse: true).toList();
```

**Comment by jaykukadiya99** [comment]
> Try to use `aggregateToStream` instead
> 
> ```dart
> var result = await collection.aggregateToStream(pipeline, allowDiskUse: true).toList();
> ```

It's working,

May I know what is the difference between both of them

**Comment by giorgiofran** [comment]
Aggregate is using the old message type that is no more supported starting from MongoDb Rel. 6.0.
Normally I have prepared a function that based on the release of the server uses the new or the old messages type, but for aggregation I only prepared the `aggregateToStream` one.

**Comment by giorgiofran** [comment]
I close this issue
