### ISSUE TITLE
Update to use Random secure constructor

### ISSUE THREAD

**Issue by Scorpiion** [mongo-dart/mongo_dart#85]
In the new Dart 1.14.0, Random added a secure constructor returning a cryptographically secure random generator.

This issue is meant to track updating to the mongodb driver where this should be used, I think at least the SCRAM-SHA-1 implementation should be updated, maybe more places? It would be a good idea to search the code base for usage of Random to see if there is any other places where it might be good to update.

https://github.com/dart-lang/sdk/blob/master/CHANGELOG.md#1140

**Comment by Pacane** [comment]
Yes I was waiting for 1.14 dev to come out. Seems like it was just released yesterday.

**Comment by Pacane** [comment]
I'll get on this ASAP, so we can make a real release.

**Comment by Scorpiion** [comment]
Sounds great! :+1:

**Comment by Scorpiion** [comment]
I also create this issue, related to this one: https://github.com/vadimtsushko/bson/issues/16

**Comment by Pacane** [comment]
Correction: 1.14 dev is not out yet.

**Comment by Scorpiion** [comment]
Ah, true.

**Comment by Pacane** [comment]
There you go @Scorpiion https://github.com/mongo-dart/mongo_dart/pull/86

Now we have to wait for 1.14 I guess. Or maybe you have a better idea to release this sooner?

**Comment by Scorpiion** [comment]
I think waiting for 1.14 sounds good, I don't have any better idea to release sooner no.

**Comment by Scorpiion** [comment]
:+1:
