### ISSUE TITLE
Support $lookup operator

### ISSUE THREAD

**Issue by RdeWilde** [mongo-dart/mongo_dart#89]
MongoDB now supports the $lookup operator to aggregrate queries. It acts like linking/joining and in most cases is more performant than loop through the results manually and fire off a seperate query for each result.
https://docs.mongodb.org/master/reference/operator/aggregation/lookup/#pipe._S_lookup

Could mongo_dart possibly implement this operator too into it's functions?

**Comment by vadimtsushko** [comment]
`DbCollection` class has funcion `aggregate`. 
I believe if you pass any valid pipeline to this method it should return valid result.
Could you try this?

**Comment by NicolasJacob** [comment]
I made some test, it do work fine. 

Anyway, you may experience issue with `aggregate` when dealing with lot of date because allowDiskUse cannot be activated. I made a MR for this https://github.com/mongo-dart/mongo_dart/pull/106

**Comment by thosakwe** [comment]
@vadimtsushko @NicolasJacob Can this issue be marked closed? Or is it still worth it to support the `$lookup` operator?

**Comment by vadimtsushko** [comment]
In my opinion it can be closed. I looks like  `aggregate` method works for this scenario (And @NicolasJacob's PR was merged, so `allowDiskUse` is supported too)

**Comment by thosakwe** [comment]
Sounds good. Closing.
