### ISSUE TITLE
Problems with createIndex

### ISSUE THREAD

**Issue by giorgiofran** [mongo-dart/mongo_dart#92]
Hi,

  I was usig mongo_dart 0.2.4 and I had a problem with the Db.createIndex function.
 The callback function that I put in the then and whenComplete functions were never called, while the catchError seemed to work.
I gave a look to the 0.2.5 beta, and I saw some differences. In particular the use of await on the call to executeMessage.call. I thougt that it could be the problem.
So I downloaded the beta and executed again my program.
Now I have a very strange problem. Every call to CreateIndex terminates in error. The error is: "DB is not open. State.CLOSED". I tried to debug. 
After the db.open function the state of the db is open.
Inside the createIndex function, on the return new Future.sync statement, it is still open.
As it enters the sync function, on the var selector = {}; statement, the db state is CLOSE.
Anyone can explain me why?
Thanks in advance,
  Giorgio

**Comment by Pacane** [comment]
Can you post some of the code you use to create the index? Thank you.

**Comment by giorgiofran** [comment]
I got the error. 
It was my code that had an error in managing the asynchronous nature of the function.
Thanks anyway,
  Giorgio
