### ISSUE TITLE
Development Status

### ISSUE THREAD

**Issue by rahulakash** [mongo-dart/mongo_dart#93]
Hello,

Firstly, thank you very much for creating the mongo_dart library. I am new to the Dart community, it's been a great experience so far. I am working on creating a Dart server application which interacts with MongoDB. Just to get some idea about the current developments in the mongo_dart library, is mongo_dart library actively maintained? I see that there has been very little activity recently in the mongo_dart library. I am just trying to get some insight to support and justify my idea of using MongoDB with Dart.

Your comments are highly appreciated.

Thanks in advance.

**Comment by lymp** [comment]
Yes, I am also interested, 
Cheers 
Steve

**Comment by Pacane** [comment]
It is maintained. This autumn I rewrote a nice part as well as rewriting all the tests. 

So far, mongo_dart fits my needs pretty well,  so I don't work as much anymore on it as I used to, however when I encounter bugs,  I try to fix them asap.

**Comment by rahulakash** [comment]
Thank you for your swift reply. This gives me some confidence in moving forward.

**Comment by Pacane** [comment]
Please note that I'm not a mongo expert though.  But if you have feature requests for features that are there on other drivers for other languages, they could be considered. 
Also, I'm always looking for contributions, remember that nobody is paid for this, yet many people use it.
