### ISSUE TITLE
Error: Unhandled exception: No top-level setter 'md5=' declared. 

### ISSUE THREAD

**Issue by rahulakash** [mongo-dart/mongo_dart#96]
Hello,

I am using Mongo_Dart GridFS to store a file uploaded from a webpage. It was working fine until past couple of weeks. But, now it is failing when I am trying to save a file to GridFS since I have updated other libraries like 'Crypto'. When I researched I found that the GridFS throws the below exception with Crypto 0.9.2 and above. I believe some of the functions are deprecated in the latest Crypto library..  

`Unhandled exception: No top-level setter 'md5=' declared.

NoSuchMethodError: method not found: 'md5='
Receiver: top-level
Arguments: ["49fcde567785d711e35ce7b8e6fbdc86"]
#0      NoSuchMethodError._throwNew (dart:core-patch/errors_patch.dart:188)
#1      GridIn.finishData (package:mongo_dart/src/gridfs/grid_in.dart:81:7)
#2      GridIn.saveChunks._onDone.<anonymous closure> (package:mongo_dart/src/gridfs/grid_in.dart:43:16)
#3      _rootRunUnary (dart:async/zone.dart:914)
#4      _CustomZone.runUnary (dart:async/zone.dart:810)
#5      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:551)
#6      _Future._propagateToListeners (dart:async/future_impl.dart:637)
#7      _Future._completeWithValue (dart:async/future_impl.dart:424)
#8      Future.wait.<anonymous closure> (dart:async/future.dart:299)
#9      _rootRunUnary (dart:async/zone.dart:914)
#10     _CustomZone.runUnary (dart:async/zone.dart:810)
#11     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:551)
#12     _Future._propagateToListeners (dart:async/future_impl.dart:637)
#13     _Future._completeWithValue (dart:async/future_impl.dart:424)
#14     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:479)
#15     _rootRun (dart:async/zone.dart:907)
#16     _CustomZone.run (dart:async/zone.dart:802)
#17     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:735)
#18     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#19     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#20     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)

Process finished with exit code 255`

**Comment by Pacane** [comment]
I'll have to check this out. You're probably right about the deprecation.

**Comment by vadimtsushko** [comment]
Hi, rahulakash. 
I've updgraded the crypto related code for current version of crypto package, so in versions >=0.2.6 that error should disappear (gridfs related mongo_dart tests now run successfully)
I close the issue. Feel free to reopen it if upgrading to current veersion of mongo_dart does not help with that issue.
