### ISSUE TITLE
Handle check failed: saw UnhandledException expected Instance

### ISSUE THREAD

**Issue by thosakwe** [mongo-dart/mongo_dart#97]
Hey, nice work on the library. Just having one small error. Trying to run a `findOne`, but I get this error:

    E:\b\build\slave\dart-sdk-windows-stable\build\sdk\runtime\vm/object.h:5205: error: Handle check failed: saw UnhandledException expected Instance

I am on Windows. Thanks in advance for your response. Pretty wild error.

**Comment by vadimtsushko** [comment]
Do you have a reproducible code? Test suites and samples i package definitely have some `findOne` that apparently work. 
Another shot - you can clone package run tests and samples locally and see would they break in your environment

**Comment by thosakwe** [comment]
Ah, I see what I did wrong. I didn't include a `where.id`.
